<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 12 Testing Hypothesis | Introduction to Statistical Thinking</title>
  <meta name="description" content="Chapter 12 Testing Hypothesis | Introduction to Statistical Thinking">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 12 Testing Hypothesis | Introduction to Statistical Thinking" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="eleuven/statthink" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 Testing Hypothesis | Introduction to Statistical Thinking" />
  
  
  

<meta name="author" content="Benjamin Yakir">


<meta name="date" content="2019-01-17">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="ChapConfidence.html">
<link rel="next" href="ChapTwoSamp.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Statistical Thinking</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="ChapIntroR.html"><a href="ChapIntroR.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="ChapIntroR.html"><a href="ChapIntroR.html#student-learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="1.2" data-path="ChapIntroR.html"><a href="ChapIntroR.html#why-learn-statistics"><i class="fa fa-check"></i><b>1.2</b> Why Learn Statistics?</a></li>
<li class="chapter" data-level="1.3" data-path="ChapIntroR.html"><a href="ChapIntroR.html#statistics"><i class="fa fa-check"></i><b>1.3</b> Statistics</a></li>
<li class="chapter" data-level="1.4" data-path="ChapIntroR.html"><a href="ChapIntroR.html#probability"><i class="fa fa-check"></i><b>1.4</b> Probability</a></li>
<li class="chapter" data-level="1.5" data-path="ChapIntroR.html"><a href="ChapIntroR.html#key-terms"><i class="fa fa-check"></i><b>1.5</b> Key Terms</a></li>
<li class="chapter" data-level="1.6" data-path="ChapIntroR.html"><a href="ChapIntroR.html#the-r-programming-environment"><i class="fa fa-check"></i><b>1.6</b> The <code>R</code> Programming Environment</a><ul>
<li class="chapter" data-level="1.6.1" data-path="ChapIntroR.html"><a href="ChapIntroR.html#some-basic-r-commands"><i class="fa fa-check"></i><b>1.6.1</b> Some Basic <code>R</code> Commands</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="ChapIntroR.html"><a href="ChapIntroR.html#exercises"><i class="fa fa-check"></i><b>1.7</b> Exercises</a></li>
<li class="chapter" data-level="1.8" data-path="ChapIntroR.html"><a href="ChapIntroR.html#summary"><i class="fa fa-check"></i><b>1.8</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ChapData.html"><a href="ChapData.html"><i class="fa fa-check"></i><b>2</b> Sampling and Data Structures</a><ul>
<li class="chapter" data-level="2.1" data-path="ChapData.html"><a href="ChapData.html#student-learning-objectives-1"><i class="fa fa-check"></i><b>2.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="ChapData.html"><a href="ChapData.html#the-sampled-data"><i class="fa fa-check"></i><b>2.2</b> The Sampled Data</a><ul>
<li class="chapter" data-level="2.2.1" data-path="ChapData.html"><a href="ChapData.html#variation-in-data"><i class="fa fa-check"></i><b>2.2.1</b> Variation in Data</a></li>
<li class="chapter" data-level="2.2.2" data-path="ChapData.html"><a href="ChapData.html#variation-in-samples"><i class="fa fa-check"></i><b>2.2.2</b> Variation in Samples</a></li>
<li class="chapter" data-level="2.2.3" data-path="ChapData.html"><a href="ChapData.html#frequency"><i class="fa fa-check"></i><b>2.2.3</b> Frequency</a></li>
<li class="chapter" data-level="2.2.4" data-path="ChapData.html"><a href="ChapData.html#critical-evaluation"><i class="fa fa-check"></i><b>2.2.4</b> Critical Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="ChapData.html"><a href="ChapData.html#readingdata"><i class="fa fa-check"></i><b>2.3</b> Reading Data into <code>R</code></a><ul>
<li class="chapter" data-level="2.3.1" data-path="ChapData.html"><a href="ChapData.html#saving-the-file-and-setting-the-working-directory"><i class="fa fa-check"></i><b>2.3.1</b> Saving the File and Setting the Working Directory</a></li>
<li class="chapter" data-level="2.3.2" data-path="ChapData.html"><a href="ChapData.html#Data_3"><i class="fa fa-check"></i><b>2.3.2</b> Reading a CSV File into <code>R</code></a></li>
<li class="chapter" data-level="2.3.3" data-path="ChapData.html"><a href="ChapData.html#data-types"><i class="fa fa-check"></i><b>2.3.3</b> Data Types</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="ChapData.html"><a href="ChapData.html#exercises-1"><i class="fa fa-check"></i><b>2.4</b> Exercises</a></li>
<li class="chapter" data-level="2.5" data-path="ChapData.html"><a href="ChapData.html#summary-1"><i class="fa fa-check"></i><b>2.5</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html"><i class="fa fa-check"></i><b>3</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="3.1" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#student-learning-objectives-2"><i class="fa fa-check"></i><b>3.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="3.2" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#displaying-data"><i class="fa fa-check"></i><b>3.2</b> Displaying Data</a><ul>
<li class="chapter" data-level="3.2.1" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#histograms"><i class="fa fa-check"></i><b>3.2.1</b> Histograms</a></li>
<li class="chapter" data-level="3.2.2" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#box-plots"><i class="fa fa-check"></i><b>3.2.2</b> Box Plots</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#measures-of-the-center-of-data"><i class="fa fa-check"></i><b>3.3</b> Measures of the Center of Data</a><ul>
<li class="chapter" data-level="3.3.1" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#skewness-the-mean-and-the-median"><i class="fa fa-check"></i><b>3.3.1</b> Skewness, the Mean and the Median</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#measures-of-the-spread-of-data"><i class="fa fa-check"></i><b>3.4</b> Measures of the Spread of Data</a></li>
<li class="chapter" data-level="3.5" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#exercises-2"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
<li class="chapter" data-level="3.6" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#summary-2"><i class="fa fa-check"></i><b>3.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#commonly-used-symbols"><i class="fa fa-check"></i>Commonly Used Symbols</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#commonly-used-expressions"><i class="fa fa-check"></i>Commonly Used Expressions</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ChapProbability.html"><a href="ChapProbability.html"><i class="fa fa-check"></i><b>4</b> Probability</a><ul>
<li class="chapter" data-level="4.1" data-path="ChapProbability.html"><a href="ChapProbability.html#student-learning-objective"><i class="fa fa-check"></i><b>4.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="4.2" data-path="ChapProbability.html"><a href="ChapProbability.html#different-forms-of-variability"><i class="fa fa-check"></i><b>4.2</b> Different Forms of Variability</a></li>
<li class="chapter" data-level="4.3" data-path="ChapProbability.html"><a href="ChapProbability.html#a-population"><i class="fa fa-check"></i><b>4.3</b> A Population</a></li>
<li class="chapter" data-level="4.4" data-path="ChapProbability.html"><a href="ChapProbability.html#random-variables"><i class="fa fa-check"></i><b>4.4</b> Random Variables</a><ul>
<li class="chapter" data-level="4.4.1" data-path="ChapProbability.html"><a href="ChapProbability.html#sample-space-and-distribution"><i class="fa fa-check"></i><b>4.4.1</b> Sample Space and Distribution</a></li>
<li class="chapter" data-level="4.4.2" data-path="ChapProbability.html"><a href="ChapProbability.html#expectation-and-standard-deviation"><i class="fa fa-check"></i><b>4.4.2</b> Expectation and Standard Deviation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="ChapProbability.html"><a href="ChapProbability.html#probability-and-statistics"><i class="fa fa-check"></i><b>4.5</b> Probability and Statistics</a></li>
<li class="chapter" data-level="4.6" data-path="ChapProbability.html"><a href="ChapProbability.html#exercises-3"><i class="fa fa-check"></i><b>4.6</b> Exercises</a></li>
<li class="chapter" data-level="4.7" data-path="ChapProbability.html"><a href="ChapProbability.html#summary-3"><i class="fa fa-check"></i><b>4.7</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#discussion-in-the-forum"><i class="fa fa-check"></i>Discussion in the Forum</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#summary-of-formulas"><i class="fa fa-check"></i>Summary of Formulas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html"><i class="fa fa-check"></i><b>5</b> Random Variables</a><ul>
<li class="chapter" data-level="5.1" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#student-learning-objective-1"><i class="fa fa-check"></i><b>5.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="5.2" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#discrete-random-variables"><i class="fa fa-check"></i><b>5.2</b> Discrete Random Variables</a><ul>
<li class="chapter" data-level="5.2.1" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#the-binomial-random-variable"><i class="fa fa-check"></i><b>5.2.1</b> The Binomial Random Variable</a></li>
<li class="chapter" data-level="5.2.2" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#the-poisson-random-variable"><i class="fa fa-check"></i><b>5.2.2</b> The Poisson Random Variable</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#RandomVar_5"><i class="fa fa-check"></i><b>5.3</b> Continuous Random Variable</a><ul>
<li class="chapter" data-level="5.3.1" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#the-uniform-random-variable"><i class="fa fa-check"></i><b>5.3.1</b> The Uniform Random Variable</a></li>
<li class="chapter" data-level="5.3.2" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#the-exponential-random-variable"><i class="fa fa-check"></i><b>5.3.2</b> The Exponential Random Variable</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#sec:RVarExercises"><i class="fa fa-check"></i><b>5.4</b> Exercises</a></li>
<li class="chapter" data-level="5.5" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#summary-4"><i class="fa fa-check"></i><b>5.5</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the Forum</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#summary-of-formulas"><i class="fa fa-check"></i>Summary of Formulas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ChapNormal.html"><a href="ChapNormal.html"><i class="fa fa-check"></i><b>6</b> The Normal Random Variable</a><ul>
<li class="chapter" data-level="6.1" data-path="ChapNormal.html"><a href="ChapNormal.html#student-learning-objective-2"><i class="fa fa-check"></i><b>6.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="6.2" data-path="ChapNormal.html"><a href="ChapNormal.html#the-normal-random-variable"><i class="fa fa-check"></i><b>6.2</b> The Normal Random Variable</a><ul>
<li class="chapter" data-level="6.2.1" data-path="ChapNormal.html"><a href="ChapNormal.html#the-normal-distribution"><i class="fa fa-check"></i><b>6.2.1</b> The Normal Distribution</a></li>
<li class="chapter" data-level="6.2.2" data-path="ChapNormal.html"><a href="ChapNormal.html#the-standard-normal-distribution"><i class="fa fa-check"></i><b>6.2.2</b> The Standard Normal Distribution</a></li>
<li class="chapter" data-level="6.2.3" data-path="ChapNormal.html"><a href="ChapNormal.html#computing-percentiles"><i class="fa fa-check"></i><b>6.2.3</b> Computing Percentiles</a></li>
<li class="chapter" data-level="6.2.4" data-path="ChapNormal.html"><a href="ChapNormal.html#outliers-and-the-normal-distribution"><i class="fa fa-check"></i><b>6.2.4</b> Outliers and the Normal Distribution</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ChapNormal.html"><a href="ChapNormal.html#approximation-of-the-binomial-distribution"><i class="fa fa-check"></i><b>6.3</b> Approximation of the Binomial Distribution</a><ul>
<li class="chapter" data-level="6.3.1" data-path="ChapNormal.html"><a href="ChapNormal.html#approximate-binomial-probabilities-and-percentiles"><i class="fa fa-check"></i><b>6.3.1</b> Approximate Binomial Probabilities and Percentiles</a></li>
<li class="chapter" data-level="6.3.2" data-path="ChapNormal.html"><a href="ChapNormal.html#continuity-corrections"><i class="fa fa-check"></i><b>6.3.2</b> Continuity Corrections</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="ChapNormal.html"><a href="ChapNormal.html#Normal4"><i class="fa fa-check"></i><b>6.4</b> Exercises</a></li>
<li class="chapter" data-level="6.5" data-path="ChapNormal.html"><a href="ChapNormal.html#summary-5"><i class="fa fa-check"></i><b>6.5</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the Forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ChapSampDist.html"><a href="ChapSampDist.html"><i class="fa fa-check"></i><b>7</b> The Sampling Distribution</a><ul>
<li class="chapter" data-level="7.1" data-path="ChapSampDist.html"><a href="ChapSampDist.html#student-learning-objective-3"><i class="fa fa-check"></i><b>7.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="7.2" data-path="ChapSampDist.html"><a href="ChapSampDist.html#the-sampling-distribution"><i class="fa fa-check"></i><b>7.2</b> The Sampling Distribution</a><ul>
<li class="chapter" data-level="7.2.1" data-path="ChapSampDist.html"><a href="ChapSampDist.html#a-random-sample"><i class="fa fa-check"></i><b>7.2.1</b> A Random Sample</a></li>
<li class="chapter" data-level="7.2.2" data-path="ChapSampDist.html"><a href="ChapSampDist.html#sampling-from-a-population"><i class="fa fa-check"></i><b>7.2.2</b> Sampling From a Population</a></li>
<li class="chapter" data-level="7.2.3" data-path="ChapSampDist.html"><a href="ChapSampDist.html#subsec:theoreticalmdls"><i class="fa fa-check"></i><b>7.2.3</b> Theoretical Models</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ChapSampDist.html"><a href="ChapSampDist.html#law-of-large-numbers-and-central-limit-theorem"><i class="fa fa-check"></i><b>7.3</b> Law of Large Numbers and Central Limit Theorem</a><ul>
<li class="chapter" data-level="7.3.1" data-path="ChapSampDist.html"><a href="ChapSampDist.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>7.3.1</b> The Law of Large Numbers</a></li>
<li class="chapter" data-level="7.3.2" data-path="ChapSampDist.html"><a href="ChapSampDist.html#the-central-limit-theorem-clt"><i class="fa fa-check"></i><b>7.3.2</b> The Central Limit Theorem (CLT)</a></li>
<li class="chapter" data-level="7.3.3" data-path="ChapSampDist.html"><a href="ChapSampDist.html#applying-the-central-limit-theorem"><i class="fa fa-check"></i><b>7.3.3</b> Applying the Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ChapSampDist.html"><a href="ChapSampDist.html#SampDistEx"><i class="fa fa-check"></i><b>7.4</b> Exercises</a></li>
<li class="chapter" data-level="7.5" data-path="ChapSampDist.html"><a href="ChapSampDist.html#summary-6"><i class="fa fa-check"></i><b>7.5</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#discussion-in-the-forum"><i class="fa fa-check"></i>Discussion in the Forum</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#summary-of-formulas"><i class="fa fa-check"></i>Summary of Formulas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="overview-and-integration.html"><a href="overview-and-integration.html"><i class="fa fa-check"></i><b>8</b> Overview and Integration</a><ul>
<li class="chapter" data-level="8.1" data-path="overview-and-integration.html"><a href="overview-and-integration.html#student-learning-objective-4"><i class="fa fa-check"></i><b>8.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="8.2" data-path="overview-and-integration.html"><a href="overview-and-integration.html#an-overview"><i class="fa fa-check"></i><b>8.2</b> An Overview</a></li>
<li class="chapter" data-level="8.3" data-path="overview-and-integration.html"><a href="overview-and-integration.html#integrated-applications"><i class="fa fa-check"></i><b>8.3</b> Integrated Applications</a><ul>
<li class="chapter" data-level="8.3.1" data-path="overview-and-integration.html"><a href="overview-and-integration.html#example-1"><i class="fa fa-check"></i><b>8.3.1</b> Example 1</a></li>
<li class="chapter" data-level="" data-path="overview-and-integration.html"><a href="overview-and-integration.html#solution"><i class="fa fa-check"></i>Solution:</a></li>
<li class="chapter" data-level="8.3.2" data-path="overview-and-integration.html"><a href="overview-and-integration.html#example-2"><i class="fa fa-check"></i><b>8.3.2</b> Example 2</a></li>
<li class="chapter" data-level="" data-path="overview-and-integration.html"><a href="overview-and-integration.html#solution-1"><i class="fa fa-check"></i>Solution:</a></li>
<li class="chapter" data-level="8.3.3" data-path="overview-and-integration.html"><a href="overview-and-integration.html#example-3"><i class="fa fa-check"></i><b>8.3.3</b> Example 3</a></li>
<li class="chapter" data-level="" data-path="overview-and-integration.html"><a href="overview-and-integration.html#solution-2"><i class="fa fa-check"></i>Solution:</a></li>
<li class="chapter" data-level="8.3.4" data-path="overview-and-integration.html"><a href="overview-and-integration.html#example-4"><i class="fa fa-check"></i><b>8.3.4</b> Example 4</a></li>
<li class="chapter" data-level="" data-path="overview-and-integration.html"><a href="overview-and-integration.html#solution-3"><i class="fa fa-check"></i>Solution</a></li>
<li class="chapter" data-level="8.3.5" data-path="overview-and-integration.html"><a href="overview-and-integration.html#example-5"><i class="fa fa-check"></i><b>8.3.5</b> Example 5</a></li>
<li class="chapter" data-level="" data-path="overview-and-integration.html"><a href="overview-and-integration.html#solution-4"><i class="fa fa-check"></i>Solution</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#discussion-in-the-forum"><i class="fa fa-check"></i>Discussion in the Forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ChapInference.html"><a href="ChapInference.html"><i class="fa fa-check"></i><b>9</b> Introduction to Statistical Inference</a><ul>
<li class="chapter" data-level="9.1" data-path="ChapInference.html"><a href="ChapInference.html#student-learning-objectives-3"><i class="fa fa-check"></i><b>9.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="9.2" data-path="ChapInference.html"><a href="ChapInference.html#key-terms-1"><i class="fa fa-check"></i><b>9.2</b> Key Terms</a></li>
<li class="chapter" data-level="9.3" data-path="ChapInference.html"><a href="ChapInference.html#the-cars-data-set"><i class="fa fa-check"></i><b>9.3</b> The Cars Data Set</a></li>
<li class="chapter" data-level="9.4" data-path="ChapInference.html"><a href="ChapInference.html#the-sampling-distribution-1"><i class="fa fa-check"></i><b>9.4</b> The Sampling Distribution</a><ul>
<li class="chapter" data-level="9.4.1" data-path="ChapInference.html"><a href="ChapInference.html#statistics-1"><i class="fa fa-check"></i><b>9.4.1</b> Statistics</a></li>
<li class="chapter" data-level="9.4.2" data-path="ChapInference.html"><a href="ChapInference.html#the-sampling-distribution-2"><i class="fa fa-check"></i><b>9.4.2</b> The Sampling Distribution</a></li>
<li class="chapter" data-level="9.4.3" data-path="ChapInference.html"><a href="ChapInference.html#theoretical-distributions-of-observations"><i class="fa fa-check"></i><b>9.4.3</b> Theoretical Distributions of Observations</a></li>
<li class="chapter" data-level="9.4.4" data-path="ChapInference.html"><a href="ChapInference.html#sampling-distribution-of-statistics"><i class="fa fa-check"></i><b>9.4.4</b> Sampling Distribution of Statistics</a></li>
<li class="chapter" data-level="9.4.5" data-path="ChapInference.html"><a href="ChapInference.html#the-normal-approximation"><i class="fa fa-check"></i><b>9.4.5</b> The Normal Approximation</a></li>
<li class="chapter" data-level="9.4.6" data-path="ChapInference.html"><a href="ChapInference.html#simulations"><i class="fa fa-check"></i><b>9.4.6</b> Simulations</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="ChapInference.html"><a href="ChapInference.html#exercises-4"><i class="fa fa-check"></i><b>9.5</b> Exercises</a></li>
<li class="chapter" data-level="9.6" data-path="ChapInference.html"><a href="ChapInference.html#summary-7"><i class="fa fa-check"></i><b>9.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ChapEstimation.html"><a href="ChapEstimation.html"><i class="fa fa-check"></i><b>10</b> Point Estimation</a><ul>
<li class="chapter" data-level="10.1" data-path="ChapEstimation.html"><a href="ChapEstimation.html#student-learning-objectives-4"><i class="fa fa-check"></i><b>10.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="10.2" data-path="ChapEstimation.html"><a href="ChapEstimation.html#estimating-parameters"><i class="fa fa-check"></i><b>10.2</b> Estimating Parameters</a></li>
<li class="chapter" data-level="10.3" data-path="ChapEstimation.html"><a href="ChapEstimation.html#EstimationExp"><i class="fa fa-check"></i><b>10.3</b> Estimation of the Expectation</a><ul>
<li class="chapter" data-level="10.3.1" data-path="ChapEstimation.html"><a href="ChapEstimation.html#the-accuracy-of-the-sample-average"><i class="fa fa-check"></i><b>10.3.1</b> The Accuracy of the Sample Average</a></li>
<li class="chapter" data-level="10.3.2" data-path="ChapEstimation.html"><a href="ChapEstimation.html#ComparingEstimators"><i class="fa fa-check"></i><b>10.3.2</b> Comparing Estimators</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="ChapEstimation.html"><a href="ChapEstimation.html#estimation-of-the-variance-and-standard-deviation"><i class="fa fa-check"></i><b>10.4</b> Estimation of the Variance and Standard Deviation</a></li>
<li class="chapter" data-level="10.5" data-path="ChapEstimation.html"><a href="ChapEstimation.html#EstimationOtherPars"><i class="fa fa-check"></i><b>10.5</b> Estimation of Other Parameters</a></li>
<li class="chapter" data-level="10.6" data-path="ChapEstimation.html"><a href="ChapEstimation.html#exercises-5"><i class="fa fa-check"></i><b>10.6</b> Exercises</a></li>
<li class="chapter" data-level="10.7" data-path="ChapEstimation.html"><a href="ChapEstimation.html#summary-8"><i class="fa fa-check"></i><b>10.7</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ChapConfidence.html"><a href="ChapConfidence.html"><i class="fa fa-check"></i><b>11</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="11.1" data-path="ChapConfidence.html"><a href="ChapConfidence.html#student-learning-objectives-5"><i class="fa fa-check"></i><b>11.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="11.2" data-path="ChapConfidence.html"><a href="ChapConfidence.html#intervals-for-mean-and-proportion"><i class="fa fa-check"></i><b>11.2</b> Intervals for Mean and Proportion</a><ul>
<li class="chapter" data-level="11.2.1" data-path="ChapConfidence.html"><a href="ChapConfidence.html#ConfidenceExamples"><i class="fa fa-check"></i><b>11.2.1</b> Examples of Confidence Intervals</a></li>
<li class="chapter" data-level="11.2.2" data-path="ChapConfidence.html"><a href="ChapConfidence.html#subsec:CImean"><i class="fa fa-check"></i><b>11.2.2</b> Confidence Intervals for the Mean</a></li>
<li class="chapter" data-level="11.2.3" data-path="ChapConfidence.html"><a href="ChapConfidence.html#subsec:CIfrac"><i class="fa fa-check"></i><b>11.2.3</b> Confidence Intervals for a Proportion</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="ChapConfidence.html"><a href="ChapConfidence.html#CInormal"><i class="fa fa-check"></i><b>11.3</b> Intervals for Normal Measurements</a><ul>
<li class="chapter" data-level="11.3.1" data-path="ChapConfidence.html"><a href="ChapConfidence.html#confidence-intervals-for-a-normal-mean"><i class="fa fa-check"></i><b>11.3.1</b> Confidence Intervals for a Normal Mean</a></li>
<li class="chapter" data-level="11.3.2" data-path="ChapConfidence.html"><a href="ChapConfidence.html#confidence-intervals-for-a-normal-variance"><i class="fa fa-check"></i><b>11.3.2</b> Confidence Intervals for a Normal Variance</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="ChapConfidence.html"><a href="ChapConfidence.html#choosing-the-sample-size"><i class="fa fa-check"></i><b>11.4</b> Choosing the Sample Size</a></li>
<li class="chapter" data-level="11.5" data-path="ChapConfidence.html"><a href="ChapConfidence.html#exercises-6"><i class="fa fa-check"></i><b>11.5</b> Exercises</a></li>
<li class="chapter" data-level="11.6" data-path="ChapConfidence.html"><a href="ChapConfidence.html#summary-9"><i class="fa fa-check"></i><b>11.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapConfidence.html"><a href="ChapConfidence.html#formulas-for-confidence-intervals-95-confidence-level"><i class="fa fa-check"></i>Formulas for Confidence Intervals, 95% Confidence Level:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ChapTesting.html"><a href="ChapTesting.html"><i class="fa fa-check"></i><b>12</b> Testing Hypothesis</a><ul>
<li class="chapter" data-level="12.1" data-path="ChapTesting.html"><a href="ChapTesting.html#student-learning-objectives-6"><i class="fa fa-check"></i><b>12.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="12.2" data-path="ChapTesting.html"><a href="ChapTesting.html#the-theory-of-hypothesis-testing"><i class="fa fa-check"></i><b>12.2</b> The Theory of Hypothesis Testing</a><ul>
<li class="chapter" data-level="12.2.1" data-path="ChapTesting.html"><a href="ChapTesting.html#an-example-of-hypothesis-testing"><i class="fa fa-check"></i><b>12.2.1</b> An Example of Hypothesis Testing</a></li>
<li class="chapter" data-level="12.2.2" data-path="ChapTesting.html"><a href="ChapTesting.html#the-structure-of-a-statistical-test-of-hypotheses"><i class="fa fa-check"></i><b>12.2.2</b> The Structure of a Statistical Test of Hypotheses</a></li>
<li class="chapter" data-level="12.2.3" data-path="ChapTesting.html"><a href="ChapTesting.html#error-types-and-error-probabilities"><i class="fa fa-check"></i><b>12.2.3</b> Error Types and Error Probabilities</a></li>
<li class="chapter" data-level="12.2.4" data-path="ChapTesting.html"><a href="ChapTesting.html#p-values"><i class="fa fa-check"></i><b>12.2.4</b> <span class="math inline">\(p\)</span>-Values</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="ChapTesting.html"><a href="ChapTesting.html#testing-hypothesis-on-expectation"><i class="fa fa-check"></i><b>12.3</b> Testing Hypothesis on Expectation</a></li>
<li class="chapter" data-level="12.4" data-path="ChapTesting.html"><a href="ChapTesting.html#TestFrac"><i class="fa fa-check"></i><b>12.4</b> Testing Hypothesis on Proportion</a></li>
<li class="chapter" data-level="12.5" data-path="ChapTesting.html"><a href="ChapTesting.html#exercises-7"><i class="fa fa-check"></i><b>12.5</b> Exercises</a></li>
<li class="chapter" data-level="12.6" data-path="ChapTesting.html"><a href="ChapTesting.html#summary-10"><i class="fa fa-check"></i><b>12.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html"><i class="fa fa-check"></i><b>13</b> Comparing Two Samples</a><ul>
<li class="chapter" data-level="13.1" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#student-learning-objectives-7"><i class="fa fa-check"></i><b>13.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="13.2" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#comparing-two-distributions"><i class="fa fa-check"></i><b>13.2</b> Comparing Two Distributions</a></li>
<li class="chapter" data-level="13.3" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#sec:ComparingMeans"><i class="fa fa-check"></i><b>13.3</b> Comparing the Sample Means</a><ul>
<li class="chapter" data-level="13.3.1" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#an-example-of-a-comparison-of-means"><i class="fa fa-check"></i><b>13.3.1</b> An Example of a Comparison of Means</a></li>
<li class="chapter" data-level="13.3.2" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#confidence-interval-for-the-difference"><i class="fa fa-check"></i><b>13.3.2</b> Confidence Interval for the Difference</a></li>
<li class="chapter" data-level="13.3.3" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#the-t-test-for-two-means"><i class="fa fa-check"></i><b>13.3.3</b> The t-Test for Two Means</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#comparing-sample-variances"><i class="fa fa-check"></i><b>13.4</b> Comparing Sample Variances</a></li>
<li class="chapter" data-level="13.5" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#exercises-8"><i class="fa fa-check"></i><b>13.5</b> Exercises</a></li>
<li class="chapter" data-level="13.6" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#summary-11"><i class="fa fa-check"></i><b>13.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ChapRegression.html"><a href="ChapRegression.html"><i class="fa fa-check"></i><b>14</b> Linear Regression</a><ul>
<li class="chapter" data-level="14.1" data-path="ChapRegression.html"><a href="ChapRegression.html#student-learning-objectives-8"><i class="fa fa-check"></i><b>14.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="14.2" data-path="ChapRegression.html"><a href="ChapRegression.html#points-and-lines"><i class="fa fa-check"></i><b>14.2</b> Points and Lines</a><ul>
<li class="chapter" data-level="14.2.1" data-path="ChapRegression.html"><a href="ChapRegression.html#the-scatter-plot"><i class="fa fa-check"></i><b>14.2.1</b> The Scatter Plot</a></li>
<li class="chapter" data-level="14.2.2" data-path="ChapRegression.html"><a href="ChapRegression.html#linear-equation"><i class="fa fa-check"></i><b>14.2.2</b> Linear Equation</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="ChapRegression.html"><a href="ChapRegression.html#linear-regression"><i class="fa fa-check"></i><b>14.3</b> Linear Regression</a><ul>
<li class="chapter" data-level="14.3.1" data-path="ChapRegression.html"><a href="ChapRegression.html#fitting-the-regression-line"><i class="fa fa-check"></i><b>14.3.1</b> Fitting the Regression Line</a></li>
<li class="chapter" data-level="14.3.2" data-path="ChapRegression.html"><a href="ChapRegression.html#subsec:Inference"><i class="fa fa-check"></i><b>14.3.2</b> Inference</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="ChapRegression.html"><a href="ChapRegression.html#r-squared-and-the-variance-of-residuals"><i class="fa fa-check"></i><b>14.4</b> R-squared and the Variance of Residuals</a></li>
<li class="chapter" data-level="14.5" data-path="ChapRegression.html"><a href="ChapRegression.html#exercises-9"><i class="fa fa-check"></i><b>14.5</b> Exercises</a></li>
<li class="chapter" data-level="14.6" data-path="ChapRegression.html"><a href="ChapRegression.html#summary-12"><i class="fa fa-check"></i><b>14.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the Forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ChapLogistic.html"><a href="ChapLogistic.html"><i class="fa fa-check"></i><b>15</b> A Bernoulli Response</a><ul>
<li class="chapter" data-level="15.1" data-path="ChapLogistic.html"><a href="ChapLogistic.html#student-learning-objectives-9"><i class="fa fa-check"></i><b>15.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="15.2" data-path="ChapLogistic.html"><a href="ChapLogistic.html#comparing-sample-proportions"><i class="fa fa-check"></i><b>15.2</b> Comparing Sample Proportions</a></li>
<li class="chapter" data-level="15.3" data-path="ChapLogistic.html"><a href="ChapLogistic.html#logistic-regression"><i class="fa fa-check"></i><b>15.3</b> Logistic Regression</a></li>
<li class="chapter" data-level="15.4" data-path="ChapLogistic.html"><a href="ChapLogistic.html#exercises-10"><i class="fa fa-check"></i><b>15.4</b> Exercises</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html"><i class="fa fa-check"></i><b>16</b> Case Studies</a><ul>
<li class="chapter" data-level="16.1" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#student-learning-objective-5"><i class="fa fa-check"></i><b>16.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="16.2" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#a-review"><i class="fa fa-check"></i><b>16.2</b> A Review</a></li>
<li class="chapter" data-level="16.3" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#case-studies"><i class="fa fa-check"></i><b>16.3</b> Case Studies</a><ul>
<li class="chapter" data-level="16.3.1" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#physicians-reactions-to-the-size-of-a-patient"><i class="fa fa-check"></i><b>16.3.1</b> Physicians’ Reactions to the Size of a Patient</a></li>
<li class="chapter" data-level="16.3.2" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#physical-strength-and-job-performance"><i class="fa fa-check"></i><b>16.3.2</b> Physical Strength and Job Performance</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#summary-13"><i class="fa fa-check"></i><b>16.4</b> Summary</a><ul>
<li class="chapter" data-level="16.4.1" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#concluding-remarks"><i class="fa fa-check"></i><b>16.4.1</b> Concluding Remarks</a></li>
<li class="chapter" data-level="16.4.2" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#discussion-in-the-forum-1"><i class="fa fa-check"></i><b>16.4.2</b> Discussion in the Forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i>Exercise Solutions</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-1"><i class="fa fa-check"></i>Chapter 1</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-1.1"><i class="fa fa-check"></i>Exercise 1.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-1.2"><i class="fa fa-check"></i>Exercise 1.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-2"><i class="fa fa-check"></i>Chapter 2</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-2.1"><i class="fa fa-check"></i>Exercise 2.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-2.2"><i class="fa fa-check"></i>Exercise 2.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-3"><i class="fa fa-check"></i>Chapter 3</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-3.1"><i class="fa fa-check"></i>Exercise 3.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-3.2"><i class="fa fa-check"></i>Exercise 3.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-4"><i class="fa fa-check"></i>Chapter 4</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-4.1"><i class="fa fa-check"></i>Exercise 4.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-4.2"><i class="fa fa-check"></i>Exercise 4.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-5"><i class="fa fa-check"></i>Chapter 5</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-5.1"><i class="fa fa-check"></i>Exercise 5.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-5.2"><i class="fa fa-check"></i>Exercise 5.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-6"><i class="fa fa-check"></i>Chapter 6</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-6.1"><i class="fa fa-check"></i>Exercise 6.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-6.2"><i class="fa fa-check"></i>Exercise 6.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-7"><i class="fa fa-check"></i>Chapter 7</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-7.1"><i class="fa fa-check"></i>Exercise 7.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-7.2"><i class="fa fa-check"></i>Exercise 7.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-9"><i class="fa fa-check"></i>Chapter 9</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-9.1"><i class="fa fa-check"></i>Exercise 9.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-9.2"><i class="fa fa-check"></i>Exercise 9.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-10"><i class="fa fa-check"></i>Chapter 10</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-10.1"><i class="fa fa-check"></i>Exercise 10.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-10.2"><i class="fa fa-check"></i>Exercise 10.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-11"><i class="fa fa-check"></i>Chapter 11</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-11.1"><i class="fa fa-check"></i>Exercise 11.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-11.2"><i class="fa fa-check"></i>Exercise 11.2</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-11.3"><i class="fa fa-check"></i>Exercise 11.3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-12"><i class="fa fa-check"></i>Chapter 12</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-12.1"><i class="fa fa-check"></i>Exercise 12.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-12.2"><i class="fa fa-check"></i>Exercise 12.2</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-12.3"><i class="fa fa-check"></i>Exercise 12.3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-13"><i class="fa fa-check"></i>Chapter 13</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-13.1"><i class="fa fa-check"></i>Exercise 13.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-13.2"><i class="fa fa-check"></i>Exercise 13.2</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-13.3"><i class="fa fa-check"></i>Exercise 13.3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-14"><i class="fa fa-check"></i>Chapter 14</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.1"><i class="fa fa-check"></i>Exercise 14.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.2"><i class="fa fa-check"></i>Exercise 14.2</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.3"><i class="fa fa-check"></i>Exercise 14.3</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.4"><i class="fa fa-check"></i>Exercise 14.4</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.5"><i class="fa fa-check"></i>Exercise 14.5</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.6"><i class="fa fa-check"></i>Exercise 14.6</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-15"><i class="fa fa-check"></i>Chapter 15</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-15.1"><i class="fa fa-check"></i>Exercise 15.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-15.2"><i class="fa fa-check"></i>Exercise 15.2</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistical Thinking</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ChapTesting" class="section level1">
<h1><span class="header-section-number">Chapter 12</span> Testing Hypothesis</h1>
<div id="student-learning-objectives-6" class="section level2">
<h2><span class="header-section-number">12.1</span> Student Learning Objectives</h2>
<p>Hypothesis testing emerges as a crucial component in decision making
where one of two competing options needs to be selected. Statistical
hypothesis testing provides formal guidelines for making such a
selection. This chapter deals with the formulation of statistical
hypothesis testing and describes the associated decision rules.
Specifically, we consider hypothesis testing in the context of the
expectation of a measurement and in the context of the probability of an
event. In subsequent chapters we deal with hypothesis testing in the
context of other parameters as well. By the end of this chapter, the
student should be able to:</p>
<ul>
<li><p>Formulate statistical hypothesis for testing.</p></li>
<li><p>Test, based on a sample, hypotheses regarding the expectation of the
measurement and the probability of an event.</p></li>
<li><p>Identify the limitations of statistical hypothesis testing and the
danger of misinterpretation of the test’s conclusions.</p></li>
</ul>
</div>
<div id="the-theory-of-hypothesis-testing" class="section level2">
<h2><span class="header-section-number">12.2</span> The Theory of Hypothesis Testing</h2>
<p>Statistical inference is used in order to detect and characterize
meaningful phenomena that may be hidden in an environment contaminated
by random noise. Hypothesis testing is an important step, typically the
first, in the process of making inferences. In this step one tries to
answer the question: “Is there a phenomena at all?”. The basic approach
is to determine whether the observed data can or cannot be reasonably
explained by a model of randomness that does not involve the phenomena.</p>
<p>In this section we introduce the structure and characteristics of
statistical hypothesis testing. We start with an informal application of
a statistical test and proceed with formal definitions. In the next
section we discuss in more detail the testing of hypotheses on the
expectation of a measurement and the testing of hypotheses on the
probability of an event. More examples are considered in subsequent
chapters.</p>
<div id="an-example-of-hypothesis-testing" class="section level3">
<h3><span class="header-section-number">12.2.1</span> An Example of Hypothesis Testing</h3>
<p>The variable “<code>price</code>” in the file “<code>cars.csv</code>” contains data on the
prices of different types of cars that were sold in the United States
during 1985. The average price of a car back then — the average of the
variable “<code>price</code>” — was $13,207. One may be interested in the
question: Do Americans pay today for cars a different price than what
they used to pay in the 80’s? Has the price of cars changed
significantly since 1985?</p>
<p>The average price of a car in the United States in 2009 was
$27,958<a href="#fn52" class="footnote-ref" id="fnref52"><sup>52</sup></a>. Clearly, this figure is higher than $13,207. However, in
order to produce a fair answer to the question we have to take into
account that, due to inflation, the prices of all products went up
during these years. A more meaningful comparison will involve the
current prices of cars in terms of 1985 Dollars. Indeed, if we take into
account inflation then we get that, on the average, the cost of today’s
cars corresponds to an average price of $13,662 in 1985 values<a href="#fn53" class="footnote-ref" id="fnref53"><sup>53</sup></a>.
This price is still higher than the prices in the 1985 but not as much.
The question we are asking is: “Is the difference between $13,207 and
$13,662 significant or is it not so?”.</p>
<p>In order to give a statistical answer to this question we carry out a
statistical test. The specific test is conducted with the aid of the
function “<code>t.test</code>”. Later we will discuss in more details some of the
arguments that may be used in this function. Currently, we simply apply
it to the data stored in the variable “<code>price</code>” to test that the
expected price is different than the $13,662, the average price of a
car in 2009, adjusted for inflation:</p>
<pre class="sourceCode r"><code class="sourceCode r">cars &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;_data/cars.csv&quot;</span>)
<span class="kw">t.test</span>(cars<span class="op">$</span>price,<span class="dt">mu=</span><span class="dv">13662</span>)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  cars$price
## t = -0.811482, df = 200, p-value = 0.41805
## alternative hypothesis: true mean is not equal to 13662
## 95 percent confidence interval:
##  12101.797 14312.462
## sample estimates:
## mean of x 
## 13207.129</code></pre>
<p>The data in the file “<code>cars.csv</code>” is read into a data frame that is
given the name “<code>cars</code>”. Afterwards, the data on prices of car types in
1985 is entered as the first argument to the function “<code>t.test</code>”. The
other argument is the expected value that we want to test, the current
average price of cars, given in terms of 1985 Dollar value. The output
of the function is reported under the title: “<code>One Sample t-test</code>”.</p>
<p>Let us read the report from the bottom up. The bottom part of the report
describes the confidence interval and the point estimate of the expected
price of a car in 1985, based on the given data. Indeed, the last line
reports the sample average of the price, which is equal to 13,207.13.
This number, the average of the 201 non-missing values of the variable
“<code>price</code>”, serves as the estimate of the expected price of a car in
1985. The 95% confidence interval of the expectation, the interval
<span class="math display">\[12101.80, 14312.46\]</span>, is presented on the 4th line from the bottom.
This is the confidence interval for the expectation that was computed in
Subsection <a href="ChapConfidence.html#subsec:CImean">11.2.2</a><a href="#fn54" class="footnote-ref" id="fnref54"><sup>54</sup></a>.</p>
<p>The information relevant to conducting the statistical test itself is
given in the upper part of the report. Specifically, it is reported that
the data in “<code>cars$price</code>” is used in order to carry out the test. Based
on this data a test statistic is computed and obtains the value of
“<code>t = -0.8115</code>”. This statistic is associated with the <span class="math inline">\(t\)</span>-distribution
with “<code>df = 200</code>” degrees of freedom. The last quantity that is being
reported is denoted the <em><span class="math inline">\(p\)</span>-value</em> and it obtains the value
“<code>p-value = 0.4181</code>”. The test may be carried out with the aid of the
value of the <span class="math inline">\(t\)</span> statistic or, more directly, using the <span class="math inline">\(p\)</span>-value.
Currently we will use the <span class="math inline">\(p\)</span>-value.</p>
<p>The test itself examines the hypothesis that the expected price of a car
in 1985 was equal to $13,662, the average price of a car in 2009, given
in 1985 values. This hypothesis is called the null hypothesis. The
alternative hypothesis is that the expected price of a car in 1985 was
not equal to that figure. The specification of the alternative
hypothesis is reported on the third line of the output of the function
“<code>t.test</code>”.</p>
<p>One may decide between the two hypothesis on the basis of the size of
the <span class="math inline">\(p\)</span>-value. The rule of thumb is to reject the null hypothesis, and
thus accept the alternative hypothesis, if the <span class="math inline">\(p\)</span>-value is less than
0.05. In the current example the <span class="math inline">\(p\)</span>-value is equal 0.4181 and is larger
than 0.05. Consequently, we may conclude that the expected price of a
car in 1985 was not significantly different than the current price of a
car.</p>
<p>In the rest of this section we give a more rigorous explanation of the
theory and practice of statistical hypothesis testing.</p>
</div>
<div id="the-structure-of-a-statistical-test-of-hypotheses" class="section level3">
<h3><span class="header-section-number">12.2.2</span> The Structure of a Statistical Test of Hypotheses</h3>
<p>The initial step in statistical inference in general, and in statistical
hypothesis testing in particular, is the formulation of the statistical
model and the identification of the parameter/s that should be
investigated. In the current situation the statistical model may
correspond to the assumption that the data in the variable “<code>price</code>” are
an instance of a <em>random</em> sample (of size <span class="math inline">\(n=201\)</span>). The parameter that
we want to investigate is the expectation of the measurement that
produced the sample. The variance of the measurement is also relevant
for the investigation.</p>
<p>After the statistical model has been set, one may split the process of
testing a statistical hypothesis into three steps: (i) formulation of
the hypotheses, (ii) specification of the test, and (iii) reaching the
final conclusion. The first two steps are carried out on the basis of
the probabilistic characteristics of the statistical model and in the
context of the sampling distribution. In principal, the first two steps
may be conducted in the planning stage prior to the collection of the
observations. Only the third step involves the actual data. In the
example that was considered in the previous subsection the third step
was applied to the data in the variable “<code>price</code>” using the function
“<code>t.test</code>”.</p>
<p><span><strong>(i) Formulating the hypotheses</strong></span>: A statistical model involves a
parameter that is the target of the investigation. In principle, this
parameter may obtain any value within a range of possible values. The
formulation of the hypothesis corresponds to splitting the range of
values into two sub-collections: a sub-collection that emerges in
response to the presence of the phenomena and a sub-collection that
emerges in response to the situation when the phenomena is absent. The
sub-collection of parameter values where the phenomena is absent is
called the <em>null hypothesis</em> and is marked as “<span class="math inline">\(H_0\)</span>”. The other
sub-collection, the one reflecting the presence of the phenomena, is
denoted the <em>alternative hypothesis</em> and is marked “<span class="math inline">\(H_1\)</span>”.</p>
<p>For example, consider the price of cars. Assume that the phenomena one
wishes to investigate is the change in the relative price of a car in
the 80’s as compared to prices today. The parameter of interest is the
expected price of cars back then, which we denote by <span class="math inline">\(\Expec(X)\)</span>. The
formulation of the statement that the expected price of cars has changed
is “<span class="math inline">\(\Expec(X) \not = 13,662\)</span>”. This statement corresponds to the
<em>presence</em> of a phenomena, to a change, and is customarily defined as
the alternative hypothesis. On the other hand, the situation
“<span class="math inline">\(\Expec(X) = 13,662\)</span>” corresponds to not having any change in the price
of cars. Hence, this situation corresponds to the <em>absence</em> of the
phenomena and is denoted the null hypothesis. In summary, in order to
investigate the change in the relative price of cars we my consider the
null hypothesis “<span class="math inline">\(H_0:\Expec(X) = 13,662\)</span>” and test it against the
alternative hypothesis “<span class="math inline">\(H_1: \Expec(X)\not = 13,662\)</span>”.</p>
<p>A variation in the formulation of the phenomena can change the
definition of the null and alternative hypotheses. For example, if the
intention is to investigate the <em>rise</em> in the price of cars then the
phenomena will correspond to the expected price in 1985 being less than
$13,662. Accordingly, the alternative hypothesis should be defined as
<span class="math inline">\(H_1: \Expec(X) &lt; 13,662\)</span>, with the null hypothesis defined as
<span class="math inline">\(H_0: \Expec(X) \geq 13,662\)</span>. Observe that in this case an expected
price larger than $13,662 relates to the phenomena of rising (relative)
prices <em>not</em> taking place.</p>
<p>On the other hand, if one would wants to investigate a <em>decrease</em> in the
price then one should define the alternative hypothesis to be
<span class="math inline">\(H_1: \Expec(X) &gt; 13,662\)</span>, with the null hypothesis being
<span class="math inline">\(H_0: \Expec(X) \leq 13,662\)</span>.</p>
<p>The type of alternative that was considered in the example,
<span class="math inline">\(H_1: \Expec(X) \not = 13,622\)</span> is called a <em>two-sided</em> alternative. The
other two types of alternative hypotheses that were considered
thereafter, <span class="math inline">\(H_1: \Expec(X) &lt; 13,662\)</span> and <span class="math inline">\(H_1: \Expec(X) &gt; 13,662\)</span>, are
both called <em>one-sided</em> alternatives.</p>
<p>In summary, the formulation of the hypothesis is a reflection of the
phenomena one wishes to examine. The setting associated with the
presence of the phenomena is denoted the alternative hypothesis and the
complimentary setting, the setting where the phenomena is absent, is
denoted the null hypothesis.</p>
<p><span><strong>(ii) Specifying the test:</strong></span> The second step in hypothesis testing
involves the selection of the decision rule, i.e. the statistical test,
to be used in order to decide between the two hypotheses. The decision
rule is composed of a statistic and a subset of values of the statistic
that correspond to the rejection of the null hypothesis. The statistic
is called the <em>test statistic</em> and the subset of values is called the
<em>rejection region</em>. The decision is to reject the null hypothesis (and
consequently choose the alternative hypothesis) if the test statistic
falls in the rejection region. Otherwise, if the test statistic does not
fall in the rejection region then the null hypothesis is selected.</p>
<p>Return to the example in which we test between <span class="math inline">\(H_0:\Expec(X) = 13,662\)</span>
and <span class="math inline">\(H_1:\Expec(X) \not= 13,662\)</span>. One may compute the statistic:</p>
<p><span class="math display">\[T = \frac{\bar X - 13,662}{S/\sqrt{n}}\;,\]</span> where <span class="math inline">\(\bar X\)</span> is the
sample average (of the variable “<code>price</code>”), <span class="math inline">\(S\)</span> is the sample standard
deviation, and <span class="math inline">\(n\)</span> is the sample size (<span class="math inline">\(n = 201\)</span> in the current
example).</p>
<p>The sample average <span class="math inline">\(\bar X\)</span> is an estimator of a expected price of the
car. In principle, the statistic <span class="math inline">\(T\)</span> measures the discrepancy between
the estimated value of the expectation (<span class="math inline">\(\bar X\)</span>) and the expected value
under the null hypothesis (<span class="math inline">\(\Expec(X) = 13,662\)</span>). This discrepancy is
measured in units of the (estimated) standard deviation of the sample
average<a href="#fn55" class="footnote-ref" id="fnref55"><sup>55</sup></a>.</p>
<p>If the null hypothesis <span class="math inline">\(H_0:\Expec(X) = 13,662\)</span> is true then the
sampling distribution of the sample average <span class="math inline">\(\bar X\)</span> should be
concentrated about the value 13,662. Values of the sample average much
larger or much smaller than this value may serve as evidence against the
null hypothesis.</p>
<p>In reflection, if the null hypothesis holds true then the values of the
sampling distribution of the statistic <span class="math inline">\(T\)</span> should tend to be in the
vicinity of 0. Values with a relative small absolute value are
consistent with the null hypothesis. On the other hand, extremely
positive or extremely negative values of the statistic indicate that the
null hypothesis is probably false.</p>
<p>It is natural to set a value <span class="math inline">\(c\)</span> and to reject the null hypothesis
whenever the absolute value of the statistic <span class="math inline">\(T\)</span> is larger than <span class="math inline">\(c\)</span>. The
resulting rejection region is of the form <span class="math inline">\(\{|T| &gt; c\}\)</span>. The rule of
thumb, again, is to take threshold <span class="math inline">\(c\)</span> to be equal the 0.975-percentile
of the <span class="math inline">\(t\)</span>-distribution on <span class="math inline">\(n-1\)</span> degrees of freedom, where <span class="math inline">\(n\)</span> is the
sample size. In the current example, the sample size is <span class="math inline">\(n=201\)</span> and the
percentile of the <span class="math inline">\(t\)</span>-distribution is <code>qt(0.975,200)</code> = 1.971896.
Consequently, the subset <span class="math inline">\(\{|T| &gt; 1.971896\}\)</span> is the rejection region of
the test.</p>
<p>A change in the hypotheses that are being tested may lead to a change in
the test statistic and/or the rejection region. For example, for testing
<span class="math inline">\(H_0: \Expec(X) \geq 13,662\)</span> versus <span class="math inline">\(H_1: \Expec(X) &lt; 13,662\)</span> one may
still use the same test statistic <span class="math inline">\(T\)</span> as before. However, only very
negative values of the statistic are inconsistent with the null
hypothesis. It turns out that the rejection region in this case is of
the form <span class="math inline">\(\{T &lt; -1.652508\}\)</span>, where <code>qt(0.05,200)</code> = -1.652508 is the
0.05-percentile of the <span class="math inline">\(t\)</span>-distribution on 200 degrees of freedom. On
the other hand, the rejection region for testing between
<span class="math inline">\(H_0: \Expec(X) \leq 13,662\)</span> and <span class="math inline">\(H_1: \Expec(X) &gt; 13,662\)</span> is
<span class="math inline">\(\{T &gt; 1.652508\}\)</span>. In this case, <code>qt(0.95,200)</code> = 1.652508 is the
0.95-percentile of the <span class="math inline">\(t\)</span>-distribution on 200 degrees of freedom.</p>
<p>Selecting the test statistic and deciding what rejection region to use
specifies the statistical test and completes the second step.</p>
<p><span><strong>(iii) Reaching a conclusion:</strong></span> After the stage is set, all that is
left is to apply the test to the observed data. This is done by
computing the observed value of the test statistic and checking whether
or not the observed value belongs to the rejection region. If it does
belong to the rejection region then the decision is to reject the null
hypothesis. Otherwise, if the statistic does not belong to the rejection
region, then the decision is to accept the null hypothesis.</p>
<p>Return to the example of testing the price of car types. The observed
value of the <span class="math inline">\(T\)</span> statistic is part of the output of the application of
the function “<code>t.test</code>” to the data. The value is “<code>t = -0.8115</code>”. As an
exercise, let us recompute directly from the data the value of the <span class="math inline">\(T\)</span>
statistic:</p>
<pre class="sourceCode r"><code class="sourceCode r">x.bar &lt;-<span class="st"> </span><span class="kw">mean</span>(cars<span class="op">$</span>price,<span class="dt">na.rm=</span><span class="ot">TRUE</span>)
x.bar</code></pre>
<pre><code>## [1] 13207.129</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">s &lt;-<span class="st"> </span><span class="kw">sd</span>(cars<span class="op">$</span>price,<span class="dt">na.rm=</span><span class="ot">TRUE</span>)</code></pre>
<p>The observed value of the sample average is <span class="math inline">\(\bar x = 13207.13\)</span> and the
observed value of the sample standard deviation is <span class="math inline">\(s = 7947.066\)</span>. The
sample size (due to having 4 missing values) is <span class="math inline">\(n=201\)</span>. The formula for
the computation of the test statistic in this example is
<span class="math inline">\(t = [\bar x - 13,662]/[s/\sqrt{n}]\)</span>. Plugging in this formula the
sample size and the computed values of the sample average and standard
deviation produces:</p>
<pre class="sourceCode r"><code class="sourceCode r">(x.bar <span class="op">-</span><span class="st"> </span><span class="dv">13662</span>)<span class="op">/</span>(s<span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">201</span>))</code></pre>
<pre><code>## [1] -0.8114824</code></pre>
<p>This value, after rounding up, is equal to the value “<code>t = -0.8115</code>”
that is reported in the output of the function “<code>t.test</code>”.</p>
<p>The critical threshold for the absolute value of the <span class="math inline">\(T\)</span> statistic on
<span class="math inline">\(201-1 = 200\)</span> degrees of freedom is <code>qt(0.975,200)</code> = 1.971896. Since
the absolute observed value (<span class="math inline">\(|t| = 0.8114824\)</span>) is less then the
threshold we get that the value of the statistic does not belong to the
rejection region (which is composed of absolute values larger than the
threshold). Consequently, we accept the null hypothesis. This null
hypothesis declares that the expected price of a car was equal to the
current expected price (after adjusting for the change in Consumer Price
Index)<a href="#fn56" class="footnote-ref" id="fnref56"><sup>56</sup></a>.</p>
</div>
<div id="error-types-and-error-probabilities" class="section level3">
<h3><span class="header-section-number">12.2.3</span> Error Types and Error Probabilities</h3>
<p>The <span class="math inline">\(T\)</span> statistic was proposed for testing a change in the price of a
car. This statistic measures the discrepancy between the sample average
price of a car and the expected value of the sample average, where the
expectation is computed under the null hypothesis. The structure of the
rejection region of the test is <span class="math inline">\(\{|T| &gt; c\}\)</span>, where <span class="math inline">\(c\)</span> is an
appropriate threshold. In the current example the value of the threshold
<span class="math inline">\(c\)</span> was set to be equal to <code>qt(0.975,200)</code> = 1.971896. In general, the
specification of the threshold <span class="math inline">\(c\)</span> depends on the error probabilities
that are associated with the test. In this section we describe these
error probabilities.</p>
<p>The process of making decisions may involve errors. In the case of
hypothesis testing one may specify two types of error. On the one hand,
the case may be that the null hypothesis is correct (in the example,
<span class="math inline">\(\Expec(X) = 13,662\)</span>). However, the data is such that the null
hypothesis is rejected (here, <span class="math inline">\(|T| &gt; 1.971896\)</span>). This error is called a
<em>Type I</em> error.</p>
<p>A different type of error occurs when the alternative hypothesis holds
(<span class="math inline">\(\Expec(X) \not= 13,662\)</span>) but the null hypothesis is not rejected
(<span class="math inline">\(|T| \leq 1.971896\)</span>). This other type of error is called <em>Type II</em>
error. A summary of the types of errors can be found in
Table <a href="ChapTesting.html#tab:Testing1">12.1</a>:</p>
<table>
<caption><span id="tab:Testing1">TABLE 12.1: </span>Error Types<span data-label="tab:Testing1"></span></caption>
<thead>
<tr class="header">
<th></th>
<th align="center"><span class="math inline">\(H_0: \Expec(X) = 13,662\)</span></th>
<th align="center"><span class="math inline">\(H_1:\Expec(X) \not= 13,662\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Accept <span class="math inline">\(H_0\)</span>: <span class="math inline">\(|T| \leq 1.971896\)</span></td>
<td align="center"></td>
<td align="center">Type II Error</td>
</tr>
<tr class="even">
<td>Reject <span class="math inline">\(H_0\)</span>: <span class="math inline">\(|T| &gt; 1.971896\)</span></td>
<td align="center">Type I Error</td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p>In statistical testing of hypothesis the two types of error are not
treated symmetrically. Rather, making a Type I error is considered more
severe than making a Type II error. Consequently, the test’s decision
rule is designed so as to assure an acceptable probability of making a
Type I error. Reducing the probability of a Type II error is desirable,
but is of secondary importance.</p>
<p>Indeed, in the example that deals with the price of car types the
threshold was set as high as <code>qt(0.975,200)</code> = 1.971896 in order to
reject the null hypothesis. It is not sufficient that the sample average
is not equal to 13,662 (corresponding to a threshold of 0), but it has
to be significantly different from the expectation under the null
hypothesis, the distance between the sample average and the null
expectation should be relatively large, in order to exclude <span class="math inline">\(H_0\)</span> as an
option.</p>
<p>The significance level of the evidence for rejecting the null hypothesis
is based on the probability of the Type I error. The probabilities
associated with the different types of error are presented in
Table <a href="ChapTesting.html#tab:Testing2">12.2</a>:</p>
<table>
<caption><span id="tab:Testing2">TABLE 12.2: </span>Error Probabilities<span data-label="tab:Testing2"></span></caption>
<thead>
<tr class="header">
<th></th>
<th align="center"><span class="math inline">\(H_0: \Expec(X) = 13,662\)</span></th>
<th align="center"><span class="math inline">\(H_1:\Expec(X) \not= 13,662\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\Prob(|T| \leq c)\)</span></td>
<td align="center"></td>
<td align="center">Prob. of Type II Error</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\Prob(|T| &gt; c)\)</span></td>
<td align="center">Significance Level</td>
<td align="center">Statistical Power</td>
</tr>
</tbody>
</table>
<p>Observe that the probability of a Type I error is called the
significance level. The significance level is set at some pre-specified
level such as 5% or 1%, with 5% being the most widely used level. In
particular, setting the threshold in the example to be equal to
<code>qt(0.975,200)</code> = 1.971896 produces a test with a 5% significance level.</p>
<p>This lack of symmetry between the two hypothesis proposes another
interpretation of the difference between the hypothesis. According to
this interpretation the null hypothesis is the one in which the cost of
making an error is greater. Thus, when one separates the collection of
parameter values into two subsets then the subset that is associated
with a more severe error is designated as the null hypothesis and the
other subset becomes the alternative.</p>
<p>For example, a new drug must pass a sequence of clinical trials before
it is approved for distribution. In these trials one may want to test
whether the new drug produces beneficial effect in comparison to the
current treatment. Naturally, the null hypothesis in this case would be
that the new drug is no better than the current treatment and the
alternative hypothesis would be that it is better. Only if the clinical
trials demonstrates a significant beneficiary effect of the new drug
would it be released for marketing.</p>
<p>In scientific research, in general, the currently accepted theory, the
conservative explanation, is designated as the null hypothesis. A claim
for novelty in the form of an alternative explanation requires strong
evidence in order for it to be accepted and be favored over the
traditional explanation. Hence, the novel explanation is designated as
the alternative hypothesis. It replaces the current theory only if the
empirical data clearly supports its. The test statistic is a summary of
the empirical data. The rejection region corresponds to values that are
unlikely to be observed according to the current theory. Obtaining a
value in the rejection region is an indication that the current theory
is probably not adequate and should be replaced by an explanation that
is more consistent with the empirical evidence.</p>
<p>The second type of error probability in Table <span class="math display">\[tab:Testing\_2\]</span> is the
probability of a Type II error. Instead of dealing directly with this
probability the tradition is to consider the complementary probability
that corresponds to the probability of <em>not</em> making a Type II error.
This complementary probability is called the <em>statistical power</em>:</p>
<p><span class="math display">\[\mbox{Statistical Power} = 1 - \mbox{Probability of Type II Error}\]</span>
The statistical power is the probability of rejecting the null
hypothesis when the state of nature is the alternative hypothesis. (In
comparison, the significance level is the probability of rejecting the
null hypothesis when the state of nature is the null hypothesis.) When
comparing two decision rules for testing hypothesis, both having the
same significance level, the one that possesses a higher statistical
power should be favored.</p>
</div>
<div id="p-values" class="section level3">
<h3><span class="header-section-number">12.2.4</span> <span class="math inline">\(p\)</span>-Values</h3>
<p>The <span class="math inline">\(p\)</span>-value is another test statistic. It is associated with a
specific test statistic and a structure of the rejection region. The
<span class="math inline">\(p\)</span>-value is equal to the significance level of the test in which the
observed value of the statistic serves as the threshold. In the current
example, where the <span class="math inline">\(T\)</span> is the underlying test statistic and the
structure of the rejection region is of the form <span class="math inline">\(\{|T| &gt; c\}\)</span> then the
<span class="math inline">\(p\)</span>-value is equal to the probability of rejecting the null hypothesis
in the case where the threshold <span class="math inline">\(c\)</span> is equal to the observed absolute
value of the <span class="math inline">\(T\)</span> statistic. In other words:</p>
<p><span class="math display">\[\mbox{$p$-value} = \Prob(|T| &gt; |t|) = \Prob(|T| &gt; |-0.8114824|)= \Prob(|T| &gt; 0.8114824)\;,\]</span>
where <span class="math inline">\(t=-0.8114824\)</span> is the observed value of the <span class="math inline">\(T\)</span> statistic and the
computation of the probability is conducted under the null hypothesis.</p>
<p>Specifically, under the null hypothesis <span class="math inline">\(H_0: \Expec(X) = 13,662\)</span> we get
that the distribution of the statistic
<span class="math inline">\(T = [\bar X - 13,662]/[S/\sqrt{n}]\)</span> is the <span class="math inline">\(t\)</span>-distribution on
<span class="math inline">\(n-1 = 200\)</span> degrees of freedom. The probability of the event
<span class="math inline">\(\{|T| &gt; 0.8114824\}\)</span> corresponds to the sum of the probabilities of
both tails of the distribution. By the symmetry of the <span class="math inline">\(t\)</span>-distribution
this equals twice the probability of the upper tail:</p>
<p><span class="math display">\[\Prob(|T| &gt; 0.8114824) = 2\cdot \Prob(T&gt; 0.8114824) = 2\cdot [1-\Prob(|T| \leq 0.8114824)]\;.\]</span>
When we compute this probability in <code>R</code> we get:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span><span class="kw">pt</span>(<span class="fl">0.8114824</span>,<span class="dv">200</span>))</code></pre>
<pre><code>## [1] 0.41805339</code></pre>
<p>This probability is equal, after rounding up, to the probability
“<code>p-value = 0.4181</code>” that is reported in the output of the function
“<code>t.test</code>”.</p>
<p>The <span class="math inline">\(p\)</span>-value is a function of the data. In the particular data set the
computed value of the <span class="math inline">\(T\)</span> statistic was -0.8114824. For a different data
set the evaluation of the statistic would have produced a different
value. As a result, the threshold that would have been used in the
computation would have been different, thereby changing the numerical
value of the <span class="math inline">\(p\)</span>-value. Being a function of the data, we conclude that
the <span class="math inline">\(p\)</span>-value is a statistic.</p>
<p>The <span class="math inline">\(p\)</span>-value is used as a test statistic by comparing its value to the
pre-defined significance level. If the significance level is 1% then the
null hypothesis is rejected for <span class="math inline">\(p\)</span>-values less that 0.01. Likewise, if
the significance level is set at the 5% level then the null hypothesis
is rejected for <span class="math inline">\(p\)</span>-values less than 0.05.</p>
<p>The statistical test that is based directly on the <span class="math inline">\(T\)</span> statistic and the
statistical test that is based on the <span class="math inline">\(p\)</span>-value are equivalent to each
other. The one rejects the null hypothesis if, and only if, the other
does so. The advantage of using the <span class="math inline">\(p\)</span>-value as the test statistic is
that no further probabilistic computations are required. The <span class="math inline">\(p\)</span>-value
is compared directly to the significance level we seek. For the test
that examines the <span class="math inline">\(T\)</span> statistic we still need to identify the threshold
associated with the given significance level.</p>
<p>In the next 2 sections we extend the discussion of the <span class="math inline">\(t\)</span>-test and give
further examples to the use of the function “<code>t.test</code>”. We also deal
with tests on probabilities of events and introduce the function
“<code>prop.test</code>” for conducting such tests.</p>
</div>
</div>
<div id="testing-hypothesis-on-expectation" class="section level2">
<h2><span class="header-section-number">12.3</span> Testing Hypothesis on Expectation</h2>
<p>Let us consider the variable “<code>dif.mpg</code>” that contains the difference in
fuel consumption between highway and city conditions. This variable was
considered in Chapter <a href="ChapConfidence.html#ChapConfidence">11</a>. Examine the distribution of
this variable:</p>
<pre class="sourceCode r"><code class="sourceCode r">dif.mpg &lt;-<span class="st"> </span>cars<span class="op">$</span>highway.mpg <span class="op">-</span><span class="st"> </span>cars<span class="op">$</span>city.mpg
<span class="kw">summary</span>(dif.mpg)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  5.0000  6.0000  5.5317  7.0000 11.0000</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">table</span>(dif.mpg))</code></pre>
<p><img src="statthink_files/figure-html/unnamed-chunk-176-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>In the first expression we created the variable “<code>dif.mpg</code>” that
contains the difference in miles-per-gallon. The difference is computed
for each car type between highway driving conditions and urban driving
condition. The summary of this variable is produced in the second
expression. Observe that the values of the variable range between 0 and
11, with 50% of the distribution concentrated between 5 and 7. The
median is 6 and the mean is 5.532. The last expression produces the bar
plot of the distribution. It turns out that the variable “<code>dif.mpg</code>”
obtains integer values.</p>
<p>In this section we test hypotheses regarding the expected difference in
fuel consumption between highway and city conditions.</p>
<p>Energy is required in order to move cars. For heavier cars more energy
is required. Consequently, one may conjecture that milage per gallon for
heavier cars is less than the milage per gallon for lighter cars.</p>
<p>The relation between the weight of the car and the difference between
the milage-per-gallon in highway and city driving conditions is less
clear. On the one hand, urban traffic involves frequent changes in speed
in comparison to highway conditions. One may presume that this change in
speed is a cause for reduced efficiency in fuel consumption. If this is
the case then one may predict that heavier cars, which require more
energy for acceleration, will be associated with a bigger difference
between highway and city driving conditions in comparison to lighter
cars.</p>
<p>One the other hand, heavier cars do less miles per gallon overall. The
difference between two smaller numbers (the milage per gallon in highway
and in city conditions for heavier cars) may tend to be smaller than the
difference between two larger numbers (the milage per gallon in highway
and in city conditions for lighter cars). If this is the case then one
may predict that heavier cars will be associated with a smaller
difference between highway and city driving conditions in comparison to
lighter cars.</p>
<p>The average difference between highway and city conditions is
approximately 5.53 for all cars. Divide the cars into to two groups of
equal size: One group is composed of the heavier cars and the other
group is composed of the lighter cars. We will examine the relation
between the weight of the car and difference in miles per gallon between
the two driving conditions by testing hypotheses separately for each
weight group<a href="#fn57" class="footnote-ref" id="fnref57"><sup>57</sup></a>. For each such group we start by testing the two-sided
hypothesis <span class="math inline">\(H_1:\Expec(X) \not = 5.53\)</span>, where <span class="math inline">\(X\)</span> is the difference
between highway and city miles-per-gallon in cars that belong to the
given weight group. After carrying the test for the two-sided
alternative we will discuss results of the application of tests for
one-sided alternatives.</p>
<p>We start by the definition of the weight groups. The variable
“<code>curb.weight</code>” measures the weight of the cars in the data frame
“<code>cars</code>”. Let us examine the summary of the content of this variable:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(cars<span class="op">$</span>curb.weight)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  1488.0  2145.0  2414.0  2555.6  2935.0  4066.0</code></pre>
<p>Half of the cars in the data frame weigh less than 2,414 lb and half the
cars weigh more. The average weight of a car is 2,556 lb. Let us take
2,414 as a threshold and denote cars below this weight as “light” and
cars above this threshold as “heavy”:</p>
<pre class="sourceCode r"><code class="sourceCode r">heavy &lt;-<span class="st"> </span>cars<span class="op">$</span>curb.weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">2414</span>
<span class="kw">table</span>(heavy)</code></pre>
<pre><code>## heavy
## FALSE  TRUE 
##   103   102</code></pre>
<p>The variable “<code>heavy</code>” indicates for each car type whether its weight is
above or below the threshold weight of 2,414 lb. The variable is
composed of a sequence with as many components as the number of
observations in the data frame “<code>cars</code>” (<span class="math inline">\(n = 205\)</span>). Each component is a
logical value: “<code>TRUE</code>” if the car is heavier than the threshold and
“<code>FALSE</code>” if it is not. When we apply the function “<code>table</code>” to this
sequence we get that 102 of the cars are heavier than the threshold and
103 are not so.</p>
<p>We would like to apply the <span class="math inline">\(t\)</span>-test first to the subset of all cars with
weight above 2,414 lb (cars that are associated with the value “<code>TRUE</code>”
in the variable “<code>heavy</code>”), and then to all cars with weights not
exceeding the threshold (cars associated with value “<code>FALSE</code>”). In the
past we showed that one may address components of a sequence using its
position in the sequence<a href="#fn58" class="footnote-ref" id="fnref58"><sup>58</sup></a>. Here we demonstrate an alternative
approach for addressing specific locations by using a sequence with
logical components.</p>
<p>In order to illustrate this second approach consider the two sequences:</p>
<pre class="sourceCode r"><code class="sourceCode r">w &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">9</span>)
d &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">13</span>,<span class="dv">22</span>,<span class="dv">0</span>,<span class="dv">12</span>,<span class="dv">6</span>,<span class="dv">20</span>)</code></pre>
<p>Say we want to select the components of the sequence “<code>d</code>” in all the
locations where the components of the sequence “<code>w</code>” obtain values
larger than 5. Consider the code:</p>
<pre class="sourceCode r"><code class="sourceCode r">w <span class="op">&gt;</span><span class="st"> </span><span class="dv">5</span></code></pre>
<pre><code>## [1] FALSE FALSE FALSE  TRUE FALSE  TRUE</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">d[w <span class="op">&gt;</span><span class="st"> </span><span class="dv">5</span>]</code></pre>
<pre><code>## [1] 12 20</code></pre>
<p>The expression “<code>w &gt; 5</code>” is a sequence of logical components, with the
value “<code>TRUE</code>” at the positions where “<code>w</code>” is above the threshold and
the value “<code>FALSE</code>” at the positions where “<code>w</code>” is below the threshold.
We may use the sequence with logical components as an index to the
sequence of the same length “<code>d</code>”. The relevant expression is
“<code>d[w &gt; 5]</code>”. The output of this expression is the sub-sequence of
elements from “<code>d</code>” that are associated with the “<code>TRUE</code>” values of the
logical sequence. Indeed, “<code>TRUE</code>” values are present at the 4th and the
6th positions of the logical sequence. Consequently, the output of the
expression “<code>d[w &gt; 5]</code>” contains the 4th and the 6th components of the
sequence “<code>d</code>”.</p>
<p>The operator “<code>!</code>”, when applied to a logical value, reverses the value.
A “<code>TRUE</code>” becomes “<code>FALSE</code>” and a “<code>FALSE</code>” becomes “<code>TRUE</code>”. Consider
the code:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="op">!</span>(w <span class="op">&gt;</span><span class="st"> </span><span class="dv">5</span>)</code></pre>
<pre><code>## [1]  TRUE  TRUE  TRUE FALSE  TRUE FALSE</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">d[<span class="op">!</span>(w <span class="op">&gt;</span><span class="st"> </span><span class="dv">5</span>)]</code></pre>
<pre><code>## [1] 13 22  0  6</code></pre>
<p>Observe that the sequence “<code>!(w &gt; 5)</code>” obtains a value of “<code>TRUE</code>” at
the positions where “<code>w</code>” is less or equal to 5. Consequently, the
output of the expression “<code>d[!(w &gt; 5)]</code>” are all the values of “<code>d</code>”
that are associated with components of “<code>w</code>” that are less or equal to
5.</p>
<p>The variable “<code>dif.mpg</code>” contains data on the difference in
miles-per-gallon between highway and city driving conditions for all the
car types. The sequence “<code>heavy</code>” identifies the car types with curb
weight above the threshold of 2,414 lb. The components of this sequence
are logical with the value “<code>TRUE</code>” at positions associated with the
heavier car types and the “<code>FALSE</code>” at positions associated with the
lighter car types. Observe that the output of the expression
“<code>dif.mpg[heavy]</code>” is the subsequence of differences in miles-per-gallon
for the cars with curb weight above the given threshold. We apply the
function “<code>t.test</code>” to this expression in order to conduct the <span class="math inline">\(t\)</span>-test
on the expectation of the variable “<code>dif.mpg</code>” for the heavier cars:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(dif.mpg[heavy],<span class="dt">mu=</span><span class="fl">5.53</span>)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  dif.mpg[heavy]
## t = -1.53853, df = 101, p-value = 0.12705
## alternative hypothesis: true mean is not equal to 5.53
## 95 percent confidence interval:
##  4.9001983 5.6096057
## sample estimates:
## mean of x 
##  5.254902</code></pre>
<p>The target population are the heavier car types. Notice that we test the
null hypothesis that expected difference among he heavier cars is equal
to 5.53 against the alternative hypothesis that the expected difference
among heavier cars is not equal to 5.53. The null hypothesis is not
rejected at the 5% significance level since the <span class="math inline">\(p\)</span>-value, which is
equal to 0.1735, is larger than 0.05. Consequently, based on the data at
hand, we cannot conclude that the expected difference in
miles-per-gallon for heavier cars is significantly different than the
average difference for all cars.</p>
<p>Observe also that the estimate of the expectation, the sample mean, is
equal to 5.254902, with a confidence interval of the form
<span class="math inline">\([4.900198, 5.609606]\)</span>.</p>
<p>Next, let us apply the same test to the lighter cars. The expression
“<code>dif.pmg[!heavy]</code>” produces the subsequence of differences in
miles-per-gallon for the cars with curb weight below the given
threshold. The application of the function “<code>t.test</code>” to this
subsequence gives:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(dif.mpg[<span class="op">!</span>heavy],<span class="dt">mu=</span><span class="fl">5.53</span>)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  dif.mpg[!heavy]
## t = 1.96923, df = 102, p-value = 0.051639
## alternative hypothesis: true mean is not equal to 5.53
## 95 percent confidence interval:
##  5.5280018 6.0836487
## sample estimates:
## mean of x 
## 5.8058252</code></pre>
<p>Again, the null hypothesis is not rejected at the 5% significance level
since a <span class="math inline">\(p\)</span>-value of 0.05164 is still larger than 0.05. However, unlike
the case for heavier cars where the <span class="math inline">\(p\)</span>-value was undeniably larger than
the threshold. In this example it is much closer to the threshold of
0.05. Consequently, we may almost conclude that the expected difference
in miles-per-gallon for lighter cars is significantly different than the
average difference for all car.</p>
<p>Why did we not reject the null hypothesis for the heavier cars but
almost did so for the lighter cars? Both tests are based on the <span class="math inline">\(T\)</span>
statistic, which measures the ratio between the deviation of the sample
average from its expectation under the null, divided by the estimate of
the standard deviation of the sample average. The value of this
statistic is “<code>t = -1.5385</code>” for heavier cars and it is “<code>t = 1.9692</code>”
for lighter cars, an absolute value of about 25% higher.</p>
<p>The deviation of the sample average for the heavier cars and the
expectation under the null is <span class="math inline">\(5.254902 - 5.53 = -0.275098\)</span>. On the
other hand, the deviation of the sample average for the lighter cars and
the expectation under the null is <span class="math inline">\(5.805825 - 5.53 = 0.275825\)</span>. The two
deviations are practically equal to each other in the absolute value.</p>
<p>The estimator of the standard deviation of the sample average is
<span class="math inline">\(S/\sqrt{n}\)</span>, where <span class="math inline">\(S\)</span> is the sample standard deviation and <span class="math inline">\(n\)</span> is the
sample size. The sample sizes, 103 for lighter cars and 102 for heavier
cars, are almost equal. Therefore, the reason for the difference in the
values of the <span class="math inline">\(T\)</span> statistics for both weight groups must be differences
in the sample standard deviations. Indeed, when we compute the sample
standard deviation for lighter and heavier cars<a href="#fn59" class="footnote-ref" id="fnref59"><sup>59</sup></a> we get that the
standard deviation for lighter cars (1.421531) is much smaller than the
standard deviation for heavier cars (1.805856):</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(dif.mpg,heavy,sd)</code></pre>
<pre><code>##     FALSE      TRUE 
## 1.4215309 1.8058556</code></pre>
<p>The important lesson to learn from this exercise is that simple minded
notion of significance and statistical significance are not the same. A
simple minded assessment of the discrepancy from the null hypothesis
will put the evidence from the data on lighter cars and the evidence
from the data on heavier cars on the same level. In both cases the
estimated value of the expectation is the same distance away from the
null value.</p>
<p>However, statistical assessment conducts the analysis in the context of
the sampling distribution. The deviation of the sample average from the
expectation is compared to the standard deviation of the sample average.
Consequently, in statistical testing of hypothesis a smaller deviation
of the sample average from the expectation under the null may be more
significant than a larger one if the sampling variability of the former
is much smaller than the sampling variability of the later.</p>
<p>Let us proceed with the demonstration of the application of the <span class="math inline">\(t\)</span>-test
by the testing of one-sided alternatives in the context of the lighter
cars. One may test the one-sided alternative <span class="math inline">\(H_1:\Expec(X) &gt; 5.53\)</span> that
the expected value of the difference in miles-per-gallon among cars with
curb weight no more than 2,414 lb is <em>greater</em> than 5.53 by the
application of the function “<code>t.test</code>” to the data on lighter cars. This
data is the output of the expression “<code>dif.mpg[!heavy]</code>”. As before, we
specify the null value of the expectation by the introduction of the
expression “<code>mu=5.53</code>”. The fact that we are interested in the testing
of the specific alternative is specified by the introduction of a new
argument of the form: “<code>alternative=greater</code>”. The default value of the
argument “<code>alternative</code>” is “<code>two.sided</code>”, which produces a test of a
two-sided alternative. By changing the value of the argument to
“<code>greater</code>” we produce a test for the appropriate one-sided alternative:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(dif.mpg[<span class="op">!</span>heavy],<span class="dt">mu=</span><span class="fl">5.53</span>,<span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  dif.mpg[!heavy]
## t = 1.96923, df = 102, p-value = 0.02582
## alternative hypothesis: true mean is greater than 5.53
## 95 percent confidence interval:
##  5.5733228       Inf
## sample estimates:
## mean of x 
## 5.8058252</code></pre>
<p>The value of the test statistic (<code>t = 1.9692</code>) is the same as for the
test of the two-sided alternative and so is the number of degrees of
freedom associated with the statistic (<code>df = 102</code>). However, the
<span class="math inline">\(p\)</span>-value is smaller (<code>p-value = 0.02582</code>), compared to the <span class="math inline">\(p\)</span>-value in
the test for the two-sided alternative (<code>p-value = 0.05164</code>). The
<span class="math inline">\(p\)</span>-value for the one-sided test is the probability under the sampling
distribution that the test statistic obtains vales larger than the
observed value of 1.9692. The <span class="math inline">\(p\)</span>-value for the two-sided test is twice
that figure since it involves also the probability of being less than
the negative of the observes value.</p>
<p>The estimated value of the expectation, the sample average, is
unchanged. However, instead of producing a confidence interval for the
expectation the report produces a <em>one-sided</em> confidence interval of the
form <span class="math inline">\([5.573323, \infty)\)</span>. Such an interval corresponds to the
<em>smallest</em> value that the expectation may reasonably obtain on the basis
of the observed data.</p>
<p>Finally, consider the test of the other one-sided alternative
<span class="math inline">\(H_1:\Expec(X) &lt; 5.53\)</span>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(dif.mpg[<span class="op">!</span>heavy],<span class="dt">mu=</span><span class="fl">5.53</span>,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  dif.mpg[!heavy]
## t = 1.96923, df = 102, p-value = 0.97418
## alternative hypothesis: true mean is less than 5.53
## 95 percent confidence interval:
##       -Inf 6.0383277
## sample estimates:
## mean of x 
## 5.8058252</code></pre>
<p>The alternative here is determined by the expression
“<code>alternative=less</code>”. The <span class="math inline">\(p\)</span>-value is equal to 0.9742, which is the
probability that the test statistic obtains values less than the
observed value of 1.9692. Clearly, the null hypothesis is not rejected
in this test.</p>
</div>
<div id="TestFrac" class="section level2">
<h2><span class="header-section-number">12.4</span> Testing Hypothesis on Proportion</h2>
<p>Consider the problem of testing hypothesis on the probability of an
event. Recall that a probability <span class="math inline">\(p\)</span> of some event can be estimated by
the observed relative frequency of the event in the sample, denoted
<span class="math inline">\(\hat P\)</span>. The estimation is associated with the Bernoulli random
variable <span class="math inline">\(X\)</span>, that obtains the value 1 when the event occurs and the
value 0 when it does not. The statistical model states that <span class="math inline">\(p\)</span> is the
expectation of <span class="math inline">\(X\)</span>. The estimator <span class="math inline">\(\hat P\)</span> is the sample average of this
measurement.</p>
<p>With this formulation we may relate the problem of testing hypotheses
formulated in terms of <span class="math inline">\(p\)</span> to the problem of tests associated to the
expectation of a measurement. For the latter problem we applied the
<span class="math inline">\(t\)</span>-test. A similar, though not identical, test is used for the problem
of testing hypothesis on proportions.</p>
<p>Assume that one in interested in testing the null hypothesis that the
probability of the event is equal to some specific value, say one half,
versus the alternative hypothesis that the probability is not equal to
this value. These hypotheses are formulated as <span class="math inline">\(H_0:p = 0.5\)</span> and
<span class="math inline">\(H_1:p\not = 0.5\)</span>.</p>
<p>The sample proportion of the event <span class="math inline">\(\hat P\)</span> is the basis for the
construction of the test statistic. Recall that the variance of the
estimator <span class="math inline">\(\hat P\)</span> is given by <span class="math inline">\(\Var(\hat P) = p(1-p)/n\)</span>. Under the null
hypothesis we get that the variance is equal to
<span class="math inline">\(\Var(\hat P) = 0.5(1-0.5)/n\)</span>. A natural test statistic is the
standardized sample proportion:</p>
<p><span class="math display">\[Z = \frac{\hat P - 0.5}{\sqrt{0.5 (1-0.5)/n}}\;,\]</span> that measures the
ratio between the deviation of the estimator from its null expected
value and the standard deviation of the estimator. The standard
deviation of the sample proportion is used in the ratio.</p>
<p>If the null hypothesis that <span class="math inline">\(p=0.5\)</span> holds true then one gets that the
value 0 is the center of the sampling distribution of the test statistic
<span class="math inline">\(Z\)</span>. Values of the statistic that are much larger or much smaller than 0
indicate that the null hypothesis is unlikely. Consequently, one may
consider a rejection region of the form <span class="math inline">\(\{|Z| &gt; c\}\)</span>, for some
threshold value <span class="math inline">\(c\)</span>. The threshold <span class="math inline">\(c\)</span> is set at a high enough level to
assure the required significance level, namely the probability under the
null hypothesis of obtaining a value in the rejection region.
Equivalently, the rejection region can be written in the form
<span class="math inline">\(\{Z^2 &gt; c^2\}\)</span>.</p>
<p>As a result of the Central Limit Theorem one may conclude that the
distribution of the test statistic is approximately Normal. Hence,
Normal computations may be used in order to produce an approximate
threshold or in order to compute an approximation for the <span class="math inline">\(p\)</span>-value.
Specifically, if <span class="math inline">\(Z\)</span> has the standard Normal distribution then <span class="math inline">\(Z^2\)</span> has
a chi-square distribution on one degree of freedom.</p>
<p>In order to illustrate the application of hypothesis testing for
proportion consider the following problem: In the previous section we
obtained the curb weight of 2,414 lb as the sample median. The weights
of half the cars in the sample were above that level and the weights of
half the cars were below this level. If this level was actually the
population median then the probability that the weight of a random car
is not exceeding this level would be equal to 0.5.</p>
<p>Let us test the hypothesis that the median weight of cars that run on
diesel is also 2,414 lb. Recall that 20 out of the 205 car types in the
sample have diesel engines. Let us use the weights of these cars in
order to test the hypothesis.</p>
<p>The variable “<code>fuel.type</code>” is a factor with two levels “<code>diesel</code>” and
“<code>gas</code>” that identify the fuel type of each car. The variable “<code>heavy</code>”
identifies for each car whether its weight is above the level of 2414 or
not. Let us produce a <span class="math inline">\(2 \times 2\)</span> table that summarizes the frequency
of each combination of weight group and the fuel type:</p>
<pre class="sourceCode r"><code class="sourceCode r">fuel &lt;-<span class="st"> </span>cars<span class="op">$</span>fuel.type
<span class="kw">table</span>(fuel,heavy)</code></pre>
<pre><code>##         heavy
## fuel     FALSE TRUE
##   diesel     6   14
##   gas       97   88</code></pre>
<p>Originally the function “<code>table</code>” was applied to a single factor and
produced a sequence with the frequencies of each level of the factor. In
the current application the input to the function are two factors<a href="#fn60" class="footnote-ref" id="fnref60"><sup>60</sup></a>.
The output is a table of frequencies. Each entry to the table
corresponds to the frequency of a combination of levels, one from the
first input factor and the other from the second input factor. In this
example we obtain that 6 cars use diesel and their curb weight was below
the threshold. There are 14 cars that use diesel and their curb weight
is above the threshold. Likewise, there are 97 light cars that use gas
and 88 heavy cars with gas engines.</p>
<p>The function “<code>prop.test</code>” produces statistical tests for proportions.
The relevant information for the current application of the function is
the fact that frequency of light diesel cars is 6 among a total number
of 20 diesel cars. The first entry to the function is the frequency of
the occurrence of the event, 6 in this case, and the second entry is the
relevant sample size, the total number of diesel cars which is 20 in the
current example:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">prop.test</span>(<span class="dv">6</span>,<span class="dv">20</span>)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  6 out of 20, null probability 0.5
## X-squared = 2.45, df = 1, p-value = 0.11752
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.12839086 0.54330713
## sample estimates:
##   p 
## 0.3</code></pre>
<p>The function produces a report that is printed on the screen. The title
identifies the test as a one-sample test of proportions. In later
chapters we will apply the same function to more complex data structures
and the title will change accordingly. The title also identifies the
fact that a continuity correction is used in the computation of the test
statistic.</p>
<p>The line under the title indicates the frequency of the event in the
sample and the sample size. (In the current example, 6 diesel cars with
weights below the threshold among a total of 20 diesel cars.) The
probability of the event, under the null hypothesis, is described. The
default value of this probability is “<code>p = 0.5</code>”, which is the proper
value in the current example. This default value can be modified by
replacing the value 0.5 by the appropriate probability.</p>
<p>The next line presents the information relevant for the test itself. The
test statistic, which is essentially the square of the <span class="math inline">\(Z\)</span> statistic
described above<a href="#fn61" class="footnote-ref" id="fnref61"><sup>61</sup></a>, obtains the value 2.45. The sampling distribution
of this statistic under the null hypothesis is, approximately, the
chi-square distribution on 1 degree of freedom. The <span class="math inline">\(p\)</span>-value, which is
the probability that chi-square distribution on 1 degree of freedom
obtains a value above 2.45, is equal to 0.1175. Consequently, the null
hypothesis is not rejected at the 5% significance level.</p>
<p>The bottom part of the report provides the confidence interval and the
point estimate for the probability of the event. The confidence interval
for the given data is <span class="math inline">\([0.1283909, 0.5433071]\)</span> and the point estimate is
<span class="math inline">\(\hat p = 6/20 = 0.3\)</span>.</p>
<p>It is interesting to note that although the deviation between the
estimated proportion <span class="math inline">\(\hat p = 0.3\)</span> and the null value of the
probability <span class="math inline">\(p = 0.5\)</span> is relatively large still the null hypothesis was
not rejected. The reason for that is the smallness of the sample,
<span class="math inline">\(n = 20\)</span>, that was used in order to test the hypothesis. Indeed, as an
exercise let us examine the application of the same test to a setting
where <span class="math inline">\(n = 200\)</span> and the number of occurrences of the event is 60:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">prop.test</span>(<span class="dv">60</span>,<span class="dv">200</span>)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  60 out of 200, null probability 0.5
## X-squared = 31.205, df = 1, p-value = 2.3217e-08
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.23844235 0.36938918
## sample estimates:
##   p 
## 0.3</code></pre>
<p>The estimated value of the probability is the same as before since
<span class="math inline">\(\hat p = 60/200 = 0.3\)</span>. However, the <span class="math inline">\(p\)</span>-value is
<span class="math inline">\(2.322 \times 10^{-8}\)</span>, which is way below the significance threshold of
0.05. In this scenario the null hypothesis is rejected with flying
colors.</p>
<p>This last example is yet another demonstration of the basic
characteristic of statistical hypothesis testing. The consideration is
based not on the discrepancy of the estimator of the parameter from the
value of the parameter under the null. Instead, it is based on the
<em>relative</em> discrepancy in comparison to the sampling variability of the
estimator. When the sample size is larger the variability is smaller.
Hence, the chances of rejecting the null hypothesis for the same
discrepancy increases.</p>
</div>
<div id="exercises-7" class="section level2">
<h2><span class="header-section-number">12.5</span> Exercises</h2>

<div class="exercise">
<p><span id="exr:unnamed-chunk-190" class="exercise"><strong>Exercise 12.1  </strong></span>Consider a medical condition that does not have a
standard treatment. The recommended design of a clinical trial for a new
treatment to such condition involves using a placebo treatment as a
control. A placebo treatment is a treatment that externally looks
identical to the actual treatment but, in reality, it does not have the
active ingredients. The reason for using placebo for control is the
“placebo effect”. Patients tent to react to the fact that they are being
treated regardless of the actual beneficial effect of the treatment.</p>
<p>As an example, consider the trial for testing magnets as a treatment for
pain that was described in Question <span class="math display">\[ex:Inference.1\]</span>. The patients
that where randomly assigned to the control (the last 21 observations in
the file “<code>magnets.csv</code>”) were treated with devises that looked like
magnets but actually were not. The goal in this exercise is to test for
the presence of a placebo effect in the case study “Magnets and Pain
Relief” of Question <span class="math display">\[ex:Inference.1\]</span> using the data in the file
“<code>magnets.csv</code>”.</p>
<ol style="list-style-type: decimal">
<li><p>Let <span class="math inline">\(X\)</span> be the measurement of change, the difference between the
score of pain before the treatment and the score after the
treatment, for patients that were treated with the inactive placebo.
Express, in terms of the expected value of <span class="math inline">\(X\)</span>, the null hypothesis
and the alternative hypothesis for a statistical test to determine
the presence of a placebo effect. The null hypothesis should reflect
the situation that the placebo effect is absent.</p></li>
<li><p>Identify the observations that can be used in order to test the
hypotheses.</p></li>
<li>Carry out the test and report your conclusion. (Use a significance
level of 5%.)</li>
</ol>
</div>


<div class="exercise">
<p><span id="exr:unnamed-chunk-191" class="exercise"><strong>Exercise 12.2  </strong></span>It is assumed, when constructing the <span class="math inline">\(t\)</span>-test, that the
measurements are Normally distributed. In this exercise we examine the
robustness of the test to divergence from the assumption. You are
required to compute the significance level of a two-sided <span class="math inline">\(t\)</span>-test of
<span class="math inline">\(H_0:\Expec(X)=4\)</span> versus <span class="math inline">\(H_1: \Expec(X) \not = 4\)</span>. Assume there are
<span class="math inline">\(n=20\)</span> observations and use a <span class="math inline">\(t\)</span>-test with a nominal 5% significance
level.</p>
<ol style="list-style-type: decimal">
<li><p>Consider the case where <span class="math inline">\(X \sim \mathrm{Exponential}(1/4)\)</span>.</p></li>
<li>Consider the case where <span class="math inline">\(X \sim \mathrm{Uniform}(0,8)\)</span>.</li>
</ol>
</div>


<div class="exercise">
<p><span id="exr:unnamed-chunk-192" class="exercise"><strong>Exercise 12.3  </strong></span>Assume that you are interested in testing
<span class="math inline">\(H_0:\Expec(X) = 20\)</span> versus <span class="math inline">\(H_1:\Expec(X)\not = 20\)</span> with a significance
level of 5% using the <span class="math inline">\(t\)</span>-test. Let the sample average, of a sample of
size <span class="math inline">\(n=55\)</span>, be equal to <span class="math inline">\(\bar x = 22.7\)</span> and the sample standard
deviation be equal to <span class="math inline">\(s = 5.4\)</span>.</p>
<ol style="list-style-type: decimal">
<li><p>Do you reject the null hypothesis?</p></li>
<li><p>Use the same information. Only now you are interested in a
significance level of 1%. Do you reject the null hypothesis?</p></li>
<li>Use the information the presentation of the exercise. But now you
are interested in testing <span class="math inline">\(H_0:\Expec(X) = 24\)</span> versus
<span class="math inline">\(H_1:\Expec(X)\not = 24\)</span> (with a significance level of 5%). Do you
reject the null hypothesis?</li>
</ol>
</div>

</div>
<div id="summary-10" class="section level2">
<h2><span class="header-section-number">12.6</span> Summary</h2>
<div id="glossary" class="section level3 unnumbered">
<h3>Glossary</h3>
<dl>
<dt>Hypothesis Testing:</dt>
<dd><p>A method for determining between two hypothesis, with one of the two
being the currently accepted hypothesis. A determination is based on
the value of the test statistic. The probability of falsely
rejecting the currently accepted hypothesis is the significance
level of the test.</p>
</dd>
<dt>Null Hypothesis (<span class="math inline">\(H_0\)</span>):</dt>
<dd><p>A sub-collection that emerges in response to the situation when the
phenomena is absent. The established scientific theory that is being
challenged. The hypothesis which is worse to erroneously reject.</p>
</dd>
<dt>Alternative Hypothesis (<span class="math inline">\(H_1\)</span>):</dt>
<dd><p>A sub-collection that emerges in response to the presence of the
investigated phenomena. The new scientific theory that challenges
the currently established theory.</p>
</dd>
<dt>Test Statistic:</dt>
<dd><p>A statistic that summarizes the data in the sample in order to
decide between the two alternative.</p>
</dd>
<dt>Rejection Region:</dt>
<dd><p>A set of values that the test statistic may obtain. If the observed
value of the test statistic belongs to the rejection region then the
null hypothesis is rejected. Otherwise, the null hypothesis is not
rejected.</p>
</dd>
<dt>Type I Error</dt>
<dd><p>The null hypothesis is correct but it is rejected by the test.</p>
</dd>
<dt>Type II Error</dt>
<dd><p>The alternative hypothesis holds but the null hypothesis is not
rejected by the test.</p>
</dd>
<dt>Significance Level:</dt>
<dd><p>The probability of a Type I error. The probability, computed under
the null hypothesis, of rejecting the null hypothesis. The test is
constructed to have a given significance level. A commonly used
significance level is 5%.</p>
</dd>
<dt>Statistical Power:</dt>
<dd><p>The probability, computed under the alternative hypothesis, of
rejecting the null hypothesis. The statistical power is equal to 1
minus the probability of a Type II error.</p>
</dd>
<dt><span class="math inline">\(p\)</span>-value:</dt>
<dd><p>A form of a test statistic. It is associated with a specific test
statistic and a structure of the rejection region. The <span class="math inline">\(p\)</span>-value is
equal to the significance level of the test in which the observed
value of the statistic serves as the threshold.</p>
</dd>
</dl>
</div>
<div id="discuss-in-the-forum" class="section level3 unnumbered">
<h3>Discuss in the forum</h3>
<p>In statistical thinking there is a tenancy towards conservatism. The
investigators, enthusiastic to obtain positive results, may prefer
favorable conclusions and may tend over-interpret the data. It is the
statistician’s role to add to the objectivity in the interpretation of
the data and to advocate caution.</p>
<p>On the other hand, the investigators may say that conservatism and
science are incompatible. If one is too cautious, if one is always
protecting oneself against the worst-case scenario, then one will not be
able to make bold new discoveries.</p>
<p>Which of the two approach do you prefer?</p>
<p>When you formulate your answer to this question it may be useful to
recall cases in your past in which you where required to analyze data or
you were exposed to other people’s analysis. Could the analysis benefit
or be harmed by either of the approaches?</p>
<p>For example, many scientific journal will tend to reject a research
paper unless the main discoveries are statistically significant
(<span class="math inline">\(p\)</span>-value <span class="math inline">\(&lt;\)</span> 5%). Should one not publish also results that show a
significance level of 10%?</p>
</div>
<div id="formulas" class="section level3 unnumbered">
<h3>Formulas:</h3>
<ul>
<li><p>Test Statistic for Expectation:
<span class="math inline">\(t = (\bar x - \mu_0)/ (s/\sqrt{n})\)</span>.</p></li>
<li><p>Two-Sided Test: Reject <span class="math inline">\(H_0\)</span> if
<span class="math inline">\(\{|t| &gt; \mbox{\texttt{qt(0.975,n-1)}}\}\)</span>.</p></li>
<li><p>Greater Than: Reject <span class="math inline">\(H_0\)</span> if
<span class="math inline">\(\{t &gt; \mbox{\texttt{qt(0.95,n-1)}}\}\)</span>.</p></li>
<li><p>Less Than: Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(\{t &lt; \mbox{\texttt{qt(0.05,n-1)}}\}\)</span>.</p></li>
</ul>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="52">
<li id="fn52"><p>Source:
“<a href="http://wiki.answers.com/Q/Average_price_of_a_car_in_2009" class="uri">http://wiki.answers.com/Q/Average_price_of_a_car_in_2009</a>”.<a href="ChapTesting.html#fnref52" class="footnote-back">↩</a></p></li>
<li id="fn53"><p>Source: “<a href="http://www.westegg.com/inflation/" class="uri">http://www.westegg.com/inflation/</a>”. The interpretation
of adjusting prices to inflation is that our comparison will
correspond to changes in the price of cars, relative to other items
that enter into the computation of the Consumer Price Index.<a href="ChapTesting.html#fnref53" class="footnote-back">↩</a></p></li>
<li id="fn54"><p>As a matter of fact, the confidence interval computed in
Subsection <span class="math display">\[subsec:Confidence\_2.1\]</span> is <span class="math display">\[12108.47, 14305.79\]</span>,
which is not identical to the confidence that appears in the report.
The reason for the discrepancy is that we used the 0.975-percentile
of the Normal distribution, 1.96, whereas the confidence interval
computed here uses the 0.975-percentile of the <span class="math inline">\(t\)</span>-distribution on
201-1=200 degrees of freedom. The latter is equal to 1.971896.
Nonetheless, for all practical purposes, the two confidence
intervals are the same.<a href="ChapTesting.html#fnref54" class="footnote-back">↩</a></p></li>
<li id="fn55"><p>If the variance of the measurement <span class="math inline">\(\Var(X)\)</span> was known one could
have use <span class="math inline">\(Z = (\bar X- - 13,662)/\sqrt{\Var{X}/n}\)</span> as a test
statistic. This statistic corresponds to the discrepancy of the
sample average from the null expectation in units of its standard
deviation, i.e. the <span class="math inline">\(z\)</span>-value of the sample average. Since the
variance of the observation is unknown, we use an estimator of the
variance (<span class="math inline">\(S^2\)</span>) instead.<a href="ChapTesting.html#fnref55" class="footnote-back">↩</a></p></li>
<li id="fn56"><p>Previously, we carried out the same test using the <span class="math inline">\(p\)</span>-value. The
computed <span class="math inline">\(p\)</span>-value in this example is 0.4181. The null hypothesis
was accepted since this value is larger than 0.05. As a matter of
fact, the test that uses the <span class="math inline">\(T\)</span> statistic as a test statistic and
reject the null hypothesis for absolute values larger than
<code>qt(0.975,n-1)</code> is equivalent to the test that uses the <span class="math inline">\(p\)</span>-value
and rejects the null hypothesis for <span class="math inline">\(p\)</span>-values less than 0.05. Below
we discuss the computation of the <span class="math inline">\(p\)</span>-value.<a href="ChapTesting.html#fnref56" class="footnote-back">↩</a></p></li>
<li id="fn57"><p>In the next chapters we will consider a more direct ways for
comparing the effect of one variable (<code>curb.weight</code> in this example)
on the distribution of another variable (<code>dif.mpg</code> in this example).
Here, instead, we investigate the effect indirectly by the
investigation of hypotheses on the expectation of the variable
<code>dif.mpg</code> separately for heavier cars and for lighter cars.<a href="ChapTesting.html#fnref57" class="footnote-back">↩</a></p></li>
<li id="fn58"><p>For example, in Question <span class="math display">\[ex:Inference.1\]</span> we referred to the
first 29 observations of the sequence “<code>change</code>” using the
expression “<code>change[1:29]</code>” and to the last 21 observations using
the expression “<code>change[30:50]</code>”.<a href="ChapTesting.html#fnref58" class="footnote-back">↩</a></p></li>
<li id="fn59"><p>The function “<code>tapply</code>” applies the function that is given as its
third argument (the function “<code>sd</code>” in this case) to each subset of
values of the sequence that is given as its first argument (the
sequence “<code>dif.mpg</code>” in the current application). The subsets are
determined by the levels of the second arguments (the sequence
“<code>heavy</code>” in this case). The output is the sample standard deviation
of the variable “<code>dif.mpg</code>” for lighter cars (the level “<code>FALSE</code>”)
and for heavier cars (the level “<code>TRUE</code>”).<a href="ChapTesting.html#fnref59" class="footnote-back">↩</a></p></li>
<li id="fn60"><p>To be more accurate, the variable “<code>heavy</code>” is not a factor but a
sequence with logical components. Nonetheless, when the function
“<code>table</code>” is applied to such a sequence it treats it as a factor
with two levels, “<code>TRUE</code>” and “<code>FALSE</code>”.<a href="ChapTesting.html#fnref60" class="footnote-back">↩</a></p></li>
<li id="fn61"><p>The test statistic that is computed by default is based on
<em>Yates’ correction for continuity</em>, which is very similar to the
continuity correction that was used in Chapter <span class="math display">\[ch:Normal\]</span> for the
Normal approximation of the Binomial distribution. Specifically, the
test statistic to the continuity correction for testing
<span class="math inline">\(H_0:p = p_0\)</span> takes the form
<span class="math inline">\([|\hat p - p_0|-0.5/n]^2/[p_0(1-p_0)/n]\)</span>. Compare this statistic
with the statistic proposed in the text that takes the form
<span class="math inline">\([\hat p - p_0]^2/[p_0(1-p_0)/n]\)</span>. The latter statistic is used if
the argument “<code>correct = FALSE</code>” is added to the function.<a href="ChapTesting.html#fnref61" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ChapConfidence.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ChapTwoSamp.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["statthink.pdf"],
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
