<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Statistical Thinking</title>
  <meta name="description" content="Introduction to Statistical Thinking">
  <meta name="generator" content="bookdown 0.5.10 and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Statistical Thinking" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="eleuven/statthink" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Statistical Thinking" />
  
  
  

<meta name="author" content="Benjamin Yakir">


<meta name="date" content="2017-11-26">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="ChapTesting.html">
<link rel="next" href="ChapRegression.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Statistical Thinking</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="ChapIntroR.html"><a href="ChapIntroR.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="ChapIntroR.html"><a href="ChapIntroR.html#student-learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="1.2" data-path="ChapIntroR.html"><a href="ChapIntroR.html#why-learn-statistics"><i class="fa fa-check"></i><b>1.2</b> Why Learn Statistics?</a></li>
<li class="chapter" data-level="1.3" data-path="ChapIntroR.html"><a href="ChapIntroR.html#statistics"><i class="fa fa-check"></i><b>1.3</b> Statistics</a></li>
<li class="chapter" data-level="1.4" data-path="ChapIntroR.html"><a href="ChapIntroR.html#probability"><i class="fa fa-check"></i><b>1.4</b> Probability</a></li>
<li class="chapter" data-level="1.5" data-path="ChapIntroR.html"><a href="ChapIntroR.html#key-terms"><i class="fa fa-check"></i><b>1.5</b> Key Terms</a></li>
<li class="chapter" data-level="1.6" data-path="ChapIntroR.html"><a href="ChapIntroR.html#the-r-programming-environment"><i class="fa fa-check"></i><b>1.6</b> The <code>R</code> Programming Environment</a><ul>
<li class="chapter" data-level="1.6.1" data-path="ChapIntroR.html"><a href="ChapIntroR.html#some-basic-r-commands"><i class="fa fa-check"></i><b>1.6.1</b> Some Basic <code>R</code> Commands</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="ChapIntroR.html"><a href="ChapIntroR.html#exercises"><i class="fa fa-check"></i><b>1.7</b> Exercises</a></li>
<li class="chapter" data-level="1.8" data-path="ChapIntroR.html"><a href="ChapIntroR.html#summary"><i class="fa fa-check"></i><b>1.8</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ChapData.html"><a href="ChapData.html"><i class="fa fa-check"></i><b>2</b> Sampling and Data Structures</a><ul>
<li class="chapter" data-level="2.1" data-path="ChapData.html"><a href="ChapData.html#student-learning-objectives-1"><i class="fa fa-check"></i><b>2.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="ChapData.html"><a href="ChapData.html#the-sampled-data"><i class="fa fa-check"></i><b>2.2</b> The Sampled Data</a><ul>
<li class="chapter" data-level="2.2.1" data-path="ChapData.html"><a href="ChapData.html#variation-in-data"><i class="fa fa-check"></i><b>2.2.1</b> Variation in Data</a></li>
<li class="chapter" data-level="2.2.2" data-path="ChapData.html"><a href="ChapData.html#variation-in-samples"><i class="fa fa-check"></i><b>2.2.2</b> Variation in Samples</a></li>
<li class="chapter" data-level="2.2.3" data-path="ChapData.html"><a href="ChapData.html#frequency"><i class="fa fa-check"></i><b>2.2.3</b> Frequency</a></li>
<li class="chapter" data-level="2.2.4" data-path="ChapData.html"><a href="ChapData.html#critical-evaluation"><i class="fa fa-check"></i><b>2.2.4</b> Critical Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="ChapData.html"><a href="ChapData.html#readingdata"><i class="fa fa-check"></i><b>2.3</b> Reading Data into <code>R</code></a><ul>
<li class="chapter" data-level="2.3.1" data-path="ChapData.html"><a href="ChapData.html#saving-the-file-and-setting-the-working-directory"><i class="fa fa-check"></i><b>2.3.1</b> Saving the File and Setting the Working Directory</a></li>
<li class="chapter" data-level="2.3.2" data-path="ChapData.html"><a href="ChapData.html#Data_3"><i class="fa fa-check"></i><b>2.3.2</b> Reading a CSV File into <code>R</code></a></li>
<li class="chapter" data-level="2.3.3" data-path="ChapData.html"><a href="ChapData.html#data-types"><i class="fa fa-check"></i><b>2.3.3</b> Data Types</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="ChapData.html"><a href="ChapData.html#exercises-1"><i class="fa fa-check"></i><b>2.4</b> Exercises</a></li>
<li class="chapter" data-level="2.5" data-path="ChapData.html"><a href="ChapData.html#summary-1"><i class="fa fa-check"></i><b>2.5</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html"><i class="fa fa-check"></i><b>3</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="3.1" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#student-learning-objectives-2"><i class="fa fa-check"></i><b>3.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="3.2" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#displaying-data"><i class="fa fa-check"></i><b>3.2</b> Displaying Data</a><ul>
<li class="chapter" data-level="3.2.1" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#histograms"><i class="fa fa-check"></i><b>3.2.1</b> Histograms</a></li>
<li class="chapter" data-level="3.2.2" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#box-plots"><i class="fa fa-check"></i><b>3.2.2</b> Box Plots</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#measures-of-the-center-of-data"><i class="fa fa-check"></i><b>3.3</b> Measures of the Center of Data</a><ul>
<li class="chapter" data-level="3.3.1" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#skewness-the-mean-and-the-median"><i class="fa fa-check"></i><b>3.3.1</b> Skewness, the Mean and the Median</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#measures-of-the-spread-of-data"><i class="fa fa-check"></i><b>3.4</b> Measures of the Spread of Data</a></li>
<li class="chapter" data-level="3.5" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#exercises-2"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
<li class="chapter" data-level="3.6" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#summary-2"><i class="fa fa-check"></i><b>3.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#commonly-used-symbols"><i class="fa fa-check"></i>Commonly Used Symbols</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#commonly-used-expressions"><i class="fa fa-check"></i>Commonly Used Expressions</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ChapProbability.html"><a href="ChapProbability.html"><i class="fa fa-check"></i><b>4</b> Probability</a><ul>
<li class="chapter" data-level="4.1" data-path="ChapProbability.html"><a href="ChapProbability.html#student-learning-objective"><i class="fa fa-check"></i><b>4.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="4.2" data-path="ChapProbability.html"><a href="ChapProbability.html#different-forms-of-variability"><i class="fa fa-check"></i><b>4.2</b> Different Forms of Variability</a></li>
<li class="chapter" data-level="4.3" data-path="ChapProbability.html"><a href="ChapProbability.html#a-population"><i class="fa fa-check"></i><b>4.3</b> A Population</a></li>
<li class="chapter" data-level="4.4" data-path="ChapProbability.html"><a href="ChapProbability.html#random-variables"><i class="fa fa-check"></i><b>4.4</b> Random Variables</a><ul>
<li class="chapter" data-level="4.4.1" data-path="ChapProbability.html"><a href="ChapProbability.html#sample-space-and-distribution"><i class="fa fa-check"></i><b>4.4.1</b> Sample Space and Distribution</a></li>
<li class="chapter" data-level="4.4.2" data-path="ChapProbability.html"><a href="ChapProbability.html#expectation-and-standard-deviation"><i class="fa fa-check"></i><b>4.4.2</b> Expectation and Standard Deviation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="ChapProbability.html"><a href="ChapProbability.html#probability-and-statistics"><i class="fa fa-check"></i><b>4.5</b> Probability and Statistics</a></li>
<li class="chapter" data-level="4.6" data-path="ChapProbability.html"><a href="ChapProbability.html#exercises-3"><i class="fa fa-check"></i><b>4.6</b> Exercises</a></li>
<li class="chapter" data-level="4.7" data-path="ChapProbability.html"><a href="ChapProbability.html#summary-3"><i class="fa fa-check"></i><b>4.7</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#discussion-in-the-forum"><i class="fa fa-check"></i>Discussion in the Forum</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#summary-of-formulas"><i class="fa fa-check"></i>Summary of Formulas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html"><i class="fa fa-check"></i><b>5</b> Random Variables</a><ul>
<li class="chapter" data-level="5.1" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#student-learning-objective-1"><i class="fa fa-check"></i><b>5.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="5.2" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#discrete-random-variables"><i class="fa fa-check"></i><b>5.2</b> Discrete Random Variables</a><ul>
<li class="chapter" data-level="5.2.1" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#the-binomial-random-variable"><i class="fa fa-check"></i><b>5.2.1</b> The Binomial Random Variable</a></li>
<li class="chapter" data-level="5.2.2" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#the-poisson-random-variable"><i class="fa fa-check"></i><b>5.2.2</b> The Poisson Random Variable</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#RandomVar_5"><i class="fa fa-check"></i><b>5.3</b> Continuous Random Variable</a><ul>
<li class="chapter" data-level="5.3.1" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#the-uniform-random-variable"><i class="fa fa-check"></i><b>5.3.1</b> The Uniform Random Variable</a></li>
<li class="chapter" data-level="5.3.2" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#the-exponential-random-variable"><i class="fa fa-check"></i><b>5.3.2</b> The Exponential Random Variable</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#sec:RVarExercises"><i class="fa fa-check"></i><b>5.4</b> Exercises</a></li>
<li class="chapter" data-level="5.5" data-path="ChapRandomVar.html"><a href="ChapRandomVar.html#summary-4"><i class="fa fa-check"></i><b>5.5</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the Forum</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#summary-of-formulas"><i class="fa fa-check"></i>Summary of Formulas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ChapNormal.html"><a href="ChapNormal.html"><i class="fa fa-check"></i><b>6</b> The Normal Random Variable</a><ul>
<li class="chapter" data-level="6.1" data-path="ChapNormal.html"><a href="ChapNormal.html#student-learning-objective-2"><i class="fa fa-check"></i><b>6.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="6.2" data-path="ChapNormal.html"><a href="ChapNormal.html#the-normal-random-variable"><i class="fa fa-check"></i><b>6.2</b> The Normal Random Variable</a><ul>
<li class="chapter" data-level="6.2.1" data-path="ChapNormal.html"><a href="ChapNormal.html#the-normal-distribution"><i class="fa fa-check"></i><b>6.2.1</b> The Normal Distribution</a></li>
<li class="chapter" data-level="6.2.2" data-path="ChapNormal.html"><a href="ChapNormal.html#the-standard-normal-distribution"><i class="fa fa-check"></i><b>6.2.2</b> The Standard Normal Distribution</a></li>
<li class="chapter" data-level="6.2.3" data-path="ChapNormal.html"><a href="ChapNormal.html#computing-percentiles"><i class="fa fa-check"></i><b>6.2.3</b> Computing Percentiles</a></li>
<li class="chapter" data-level="6.2.4" data-path="ChapNormal.html"><a href="ChapNormal.html#outliers-and-the-normal-distribution"><i class="fa fa-check"></i><b>6.2.4</b> Outliers and the Normal Distribution</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ChapNormal.html"><a href="ChapNormal.html#approximation-of-the-binomial-distribution"><i class="fa fa-check"></i><b>6.3</b> Approximation of the Binomial Distribution</a><ul>
<li class="chapter" data-level="6.3.1" data-path="ChapNormal.html"><a href="ChapNormal.html#approximate-binomial-probabilities-and-percentiles"><i class="fa fa-check"></i><b>6.3.1</b> Approximate Binomial Probabilities and Percentiles</a></li>
<li class="chapter" data-level="6.3.2" data-path="ChapNormal.html"><a href="ChapNormal.html#continuity-corrections"><i class="fa fa-check"></i><b>6.3.2</b> Continuity Corrections</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="ChapNormal.html"><a href="ChapNormal.html#Normal4"><i class="fa fa-check"></i><b>6.4</b> Exercises</a></li>
<li class="chapter" data-level="6.5" data-path="ChapNormal.html"><a href="ChapNormal.html#summary-5"><i class="fa fa-check"></i><b>6.5</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the Forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ChapSampDist.html"><a href="ChapSampDist.html"><i class="fa fa-check"></i><b>7</b> The Sampling Distribution</a><ul>
<li class="chapter" data-level="7.1" data-path="ChapSampDist.html"><a href="ChapSampDist.html#student-learning-objective-3"><i class="fa fa-check"></i><b>7.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="7.2" data-path="ChapSampDist.html"><a href="ChapSampDist.html#the-sampling-distribution"><i class="fa fa-check"></i><b>7.2</b> The Sampling Distribution</a><ul>
<li class="chapter" data-level="7.2.1" data-path="ChapSampDist.html"><a href="ChapSampDist.html#a-random-sample"><i class="fa fa-check"></i><b>7.2.1</b> A Random Sample</a></li>
<li class="chapter" data-level="7.2.2" data-path="ChapSampDist.html"><a href="ChapSampDist.html#sampling-from-a-population"><i class="fa fa-check"></i><b>7.2.2</b> Sampling From a Population</a></li>
<li class="chapter" data-level="7.2.3" data-path="ChapSampDist.html"><a href="ChapSampDist.html#subsec:theoreticalmdls"><i class="fa fa-check"></i><b>7.2.3</b> Theoretical Models</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ChapSampDist.html"><a href="ChapSampDist.html#law-of-large-numbers-and-central-limit-theorem"><i class="fa fa-check"></i><b>7.3</b> Law of Large Numbers and Central Limit Theorem</a><ul>
<li class="chapter" data-level="7.3.1" data-path="ChapSampDist.html"><a href="ChapSampDist.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>7.3.1</b> The Law of Large Numbers</a></li>
<li class="chapter" data-level="7.3.2" data-path="ChapSampDist.html"><a href="ChapSampDist.html#the-central-limit-theorem-clt"><i class="fa fa-check"></i><b>7.3.2</b> The Central Limit Theorem (CLT)</a></li>
<li class="chapter" data-level="7.3.3" data-path="ChapSampDist.html"><a href="ChapSampDist.html#applying-the-central-limit-theorem"><i class="fa fa-check"></i><b>7.3.3</b> Applying the Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ChapSampDist.html"><a href="ChapSampDist.html#SampDistEx"><i class="fa fa-check"></i><b>7.4</b> Exercises</a></li>
<li class="chapter" data-level="7.5" data-path="ChapSampDist.html"><a href="ChapSampDist.html#summary-6"><i class="fa fa-check"></i><b>7.5</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#discussion-in-the-forum"><i class="fa fa-check"></i>Discussion in the Forum</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#summary-of-formulas"><i class="fa fa-check"></i>Summary of Formulas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="overview-and-integration.html"><a href="overview-and-integration.html"><i class="fa fa-check"></i><b>8</b> Overview and Integration</a><ul>
<li class="chapter" data-level="8.1" data-path="overview-and-integration.html"><a href="overview-and-integration.html#student-learning-objective-4"><i class="fa fa-check"></i><b>8.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="8.2" data-path="overview-and-integration.html"><a href="overview-and-integration.html#an-overview"><i class="fa fa-check"></i><b>8.2</b> An Overview</a></li>
<li class="chapter" data-level="8.3" data-path="overview-and-integration.html"><a href="overview-and-integration.html#integrated-applications"><i class="fa fa-check"></i><b>8.3</b> Integrated Applications</a><ul>
<li class="chapter" data-level="8.3.1" data-path="overview-and-integration.html"><a href="overview-and-integration.html#example-1"><i class="fa fa-check"></i><b>8.3.1</b> Example 1</a></li>
<li class="chapter" data-level="" data-path="overview-and-integration.html"><a href="overview-and-integration.html#solution"><i class="fa fa-check"></i>Solution:</a></li>
<li class="chapter" data-level="8.3.2" data-path="overview-and-integration.html"><a href="overview-and-integration.html#example-2"><i class="fa fa-check"></i><b>8.3.2</b> Example 2</a></li>
<li class="chapter" data-level="" data-path="overview-and-integration.html"><a href="overview-and-integration.html#solution-1"><i class="fa fa-check"></i>Solution:</a></li>
<li class="chapter" data-level="8.3.3" data-path="overview-and-integration.html"><a href="overview-and-integration.html#example-3"><i class="fa fa-check"></i><b>8.3.3</b> Example 3</a></li>
<li class="chapter" data-level="" data-path="overview-and-integration.html"><a href="overview-and-integration.html#solution-2"><i class="fa fa-check"></i>Solution:</a></li>
<li class="chapter" data-level="8.3.4" data-path="overview-and-integration.html"><a href="overview-and-integration.html#example-4"><i class="fa fa-check"></i><b>8.3.4</b> Example 4</a></li>
<li class="chapter" data-level="" data-path="overview-and-integration.html"><a href="overview-and-integration.html#solution-3"><i class="fa fa-check"></i>Solution</a></li>
<li class="chapter" data-level="8.3.5" data-path="overview-and-integration.html"><a href="overview-and-integration.html#example-5"><i class="fa fa-check"></i><b>8.3.5</b> Example 5</a></li>
<li class="chapter" data-level="" data-path="overview-and-integration.html"><a href="overview-and-integration.html#solution-4"><i class="fa fa-check"></i>Solution</a></li>
<li class="chapter" data-level="" data-path="ChapProbability.html"><a href="ChapProbability.html#discussion-in-the-forum"><i class="fa fa-check"></i>Discussion in the Forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ChapInference.html"><a href="ChapInference.html"><i class="fa fa-check"></i><b>9</b> Introduction to Statistical Inference</a><ul>
<li class="chapter" data-level="9.1" data-path="ChapInference.html"><a href="ChapInference.html#student-learning-objectives-3"><i class="fa fa-check"></i><b>9.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="9.2" data-path="ChapInference.html"><a href="ChapInference.html#key-terms-1"><i class="fa fa-check"></i><b>9.2</b> Key Terms</a></li>
<li class="chapter" data-level="9.3" data-path="ChapInference.html"><a href="ChapInference.html#the-cars-data-set"><i class="fa fa-check"></i><b>9.3</b> The Cars Data Set</a></li>
<li class="chapter" data-level="9.4" data-path="ChapSampDist.html"><a href="ChapSampDist.html#the-sampling-distribution"><i class="fa fa-check"></i><b>9.4</b> The Sampling Distribution</a><ul>
<li class="chapter" data-level="9.4.1" data-path="ChapInference.html"><a href="ChapInference.html#statistics-1"><i class="fa fa-check"></i><b>9.4.1</b> Statistics</a></li>
<li class="chapter" data-level="9.4.2" data-path="ChapInference.html"><a href="ChapInference.html#the-sampling-distribution-1"><i class="fa fa-check"></i><b>9.4.2</b> The Sampling Distribution</a></li>
<li class="chapter" data-level="9.4.3" data-path="ChapInference.html"><a href="ChapInference.html#theoretical-distributions-of-observations"><i class="fa fa-check"></i><b>9.4.3</b> Theoretical Distributions of Observations</a></li>
<li class="chapter" data-level="9.4.4" data-path="ChapInference.html"><a href="ChapInference.html#sampling-distribution-of-statistics"><i class="fa fa-check"></i><b>9.4.4</b> Sampling Distribution of Statistics</a></li>
<li class="chapter" data-level="9.4.5" data-path="ChapInference.html"><a href="ChapInference.html#the-normal-approximation"><i class="fa fa-check"></i><b>9.4.5</b> The Normal Approximation</a></li>
<li class="chapter" data-level="9.4.6" data-path="ChapInference.html"><a href="ChapInference.html#simulations"><i class="fa fa-check"></i><b>9.4.6</b> Simulations</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="ChapInference.html"><a href="ChapInference.html#exercises-4"><i class="fa fa-check"></i><b>9.5</b> Exercises</a></li>
<li class="chapter" data-level="9.6" data-path="ChapInference.html"><a href="ChapInference.html#summary-7"><i class="fa fa-check"></i><b>9.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ChapEstimation.html"><a href="ChapEstimation.html"><i class="fa fa-check"></i><b>10</b> Point Estimation</a><ul>
<li class="chapter" data-level="10.1" data-path="ChapEstimation.html"><a href="ChapEstimation.html#student-learning-objectives-4"><i class="fa fa-check"></i><b>10.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="10.2" data-path="ChapEstimation.html"><a href="ChapEstimation.html#estimating-parameters"><i class="fa fa-check"></i><b>10.2</b> Estimating Parameters</a></li>
<li class="chapter" data-level="10.3" data-path="ChapEstimation.html"><a href="ChapEstimation.html#EstimationExp"><i class="fa fa-check"></i><b>10.3</b> Estimation of the Expectation</a><ul>
<li class="chapter" data-level="10.3.1" data-path="ChapEstimation.html"><a href="ChapEstimation.html#the-accuracy-of-the-sample-average"><i class="fa fa-check"></i><b>10.3.1</b> The Accuracy of the Sample Average</a></li>
<li class="chapter" data-level="10.3.2" data-path="ChapEstimation.html"><a href="ChapEstimation.html#ComparingEstimators"><i class="fa fa-check"></i><b>10.3.2</b> Comparing Estimators</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="ChapEstimation.html"><a href="ChapEstimation.html#estimation-of-the-variance-and-standard-deviation"><i class="fa fa-check"></i><b>10.4</b> Estimation of the Variance and Standard Deviation</a></li>
<li class="chapter" data-level="10.5" data-path="ChapEstimation.html"><a href="ChapEstimation.html#EstimationOtherPars"><i class="fa fa-check"></i><b>10.5</b> Estimation of Other Parameters</a></li>
<li class="chapter" data-level="10.6" data-path="ChapEstimation.html"><a href="ChapEstimation.html#exercises-5"><i class="fa fa-check"></i><b>10.6</b> Exercises</a></li>
<li class="chapter" data-level="10.7" data-path="ChapEstimation.html"><a href="ChapEstimation.html#summary-8"><i class="fa fa-check"></i><b>10.7</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ChapConfidence.html"><a href="ChapConfidence.html"><i class="fa fa-check"></i><b>11</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="11.1" data-path="ChapConfidence.html"><a href="ChapConfidence.html#student-learning-objectives-5"><i class="fa fa-check"></i><b>11.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="11.2" data-path="ChapConfidence.html"><a href="ChapConfidence.html#intervals-for-mean-and-proportion"><i class="fa fa-check"></i><b>11.2</b> Intervals for Mean and Proportion</a><ul>
<li class="chapter" data-level="11.2.1" data-path="ChapConfidence.html"><a href="ChapConfidence.html#ConfidenceExamples"><i class="fa fa-check"></i><b>11.2.1</b> Examples of Confidence Intervals</a></li>
<li class="chapter" data-level="11.2.2" data-path="ChapConfidence.html"><a href="ChapConfidence.html#subsec:CImean"><i class="fa fa-check"></i><b>11.2.2</b> Confidence Intervals for the Mean</a></li>
<li class="chapter" data-level="11.2.3" data-path="ChapConfidence.html"><a href="ChapConfidence.html#subsec:CIfrac"><i class="fa fa-check"></i><b>11.2.3</b> Confidence Intervals for a Proportion</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="ChapConfidence.html"><a href="ChapConfidence.html#CInormal"><i class="fa fa-check"></i><b>11.3</b> Intervals for Normal Measurements</a><ul>
<li class="chapter" data-level="11.3.1" data-path="ChapConfidence.html"><a href="ChapConfidence.html#confidence-intervals-for-a-normal-mean"><i class="fa fa-check"></i><b>11.3.1</b> Confidence Intervals for a Normal Mean</a></li>
<li class="chapter" data-level="11.3.2" data-path="ChapConfidence.html"><a href="ChapConfidence.html#confidence-intervals-for-a-normal-variance"><i class="fa fa-check"></i><b>11.3.2</b> Confidence Intervals for a Normal Variance</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="ChapConfidence.html"><a href="ChapConfidence.html#choosing-the-sample-size"><i class="fa fa-check"></i><b>11.4</b> Choosing the Sample Size</a></li>
<li class="chapter" data-level="11.5" data-path="ChapConfidence.html"><a href="ChapConfidence.html#exercises-6"><i class="fa fa-check"></i><b>11.5</b> Exercises</a></li>
<li class="chapter" data-level="11.6" data-path="ChapConfidence.html"><a href="ChapConfidence.html#summary-9"><i class="fa fa-check"></i><b>11.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapConfidence.html"><a href="ChapConfidence.html#formulas-for-confidence-intervals-95-confidence-level"><i class="fa fa-check"></i>Formulas for Confidence Intervals, 95% Confidence Level:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ChapTesting.html"><a href="ChapTesting.html"><i class="fa fa-check"></i><b>12</b> Testing Hypothesis</a><ul>
<li class="chapter" data-level="12.1" data-path="ChapTesting.html"><a href="ChapTesting.html#student-learning-objectives-6"><i class="fa fa-check"></i><b>12.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="12.2" data-path="ChapTesting.html"><a href="ChapTesting.html#the-theory-of-hypothesis-testing"><i class="fa fa-check"></i><b>12.2</b> The Theory of Hypothesis Testing</a><ul>
<li class="chapter" data-level="12.2.1" data-path="ChapTesting.html"><a href="ChapTesting.html#an-example-of-hypothesis-testing"><i class="fa fa-check"></i><b>12.2.1</b> An Example of Hypothesis Testing</a></li>
<li class="chapter" data-level="12.2.2" data-path="ChapTesting.html"><a href="ChapTesting.html#the-structure-of-a-statistical-test-of-hypotheses"><i class="fa fa-check"></i><b>12.2.2</b> The Structure of a Statistical Test of Hypotheses</a></li>
<li class="chapter" data-level="12.2.3" data-path="ChapTesting.html"><a href="ChapTesting.html#error-types-and-error-probabilities"><i class="fa fa-check"></i><b>12.2.3</b> Error Types and Error Probabilities</a></li>
<li class="chapter" data-level="12.2.4" data-path="ChapTesting.html"><a href="ChapTesting.html#p-values"><i class="fa fa-check"></i><b>12.2.4</b> <span class="math inline">\(p\)</span>-Values</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="ChapTesting.html"><a href="ChapTesting.html#testing-hypothesis-on-expectation"><i class="fa fa-check"></i><b>12.3</b> Testing Hypothesis on Expectation</a></li>
<li class="chapter" data-level="12.4" data-path="ChapTesting.html"><a href="ChapTesting.html#TestFrac"><i class="fa fa-check"></i><b>12.4</b> Testing Hypothesis on Proportion</a></li>
<li class="chapter" data-level="12.5" data-path="ChapTesting.html"><a href="ChapTesting.html#exercises-7"><i class="fa fa-check"></i><b>12.5</b> Exercises</a></li>
<li class="chapter" data-level="12.6" data-path="ChapTesting.html"><a href="ChapTesting.html#summary-10"><i class="fa fa-check"></i><b>12.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html"><i class="fa fa-check"></i><b>13</b> Comparing Two Samples</a><ul>
<li class="chapter" data-level="13.1" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#student-learning-objectives-7"><i class="fa fa-check"></i><b>13.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="13.2" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#comparing-two-distributions"><i class="fa fa-check"></i><b>13.2</b> Comparing Two Distributions</a></li>
<li class="chapter" data-level="13.3" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#sec:ComparingMeans"><i class="fa fa-check"></i><b>13.3</b> Comparing the Sample Means</a><ul>
<li class="chapter" data-level="13.3.1" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#an-example-of-a-comparison-of-means"><i class="fa fa-check"></i><b>13.3.1</b> An Example of a Comparison of Means</a></li>
<li class="chapter" data-level="13.3.2" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#confidence-interval-for-the-difference"><i class="fa fa-check"></i><b>13.3.2</b> Confidence Interval for the Difference</a></li>
<li class="chapter" data-level="13.3.3" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#the-t-test-for-two-means"><i class="fa fa-check"></i><b>13.3.3</b> The t-Test for Two Means</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#comparing-sample-variances"><i class="fa fa-check"></i><b>13.4</b> Comparing Sample Variances</a></li>
<li class="chapter" data-level="13.5" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#exercises-8"><i class="fa fa-check"></i><b>13.5</b> Exercises</a></li>
<li class="chapter" data-level="13.6" data-path="ChapTwoSamp.html"><a href="ChapTwoSamp.html#summary-11"><i class="fa fa-check"></i><b>13.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ChapRegression.html"><a href="ChapRegression.html"><i class="fa fa-check"></i><b>14</b> Linear Regression</a><ul>
<li class="chapter" data-level="14.1" data-path="ChapRegression.html"><a href="ChapRegression.html#student-learning-objectives-8"><i class="fa fa-check"></i><b>14.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="14.2" data-path="ChapRegression.html"><a href="ChapRegression.html#points-and-lines"><i class="fa fa-check"></i><b>14.2</b> Points and Lines</a><ul>
<li class="chapter" data-level="14.2.1" data-path="ChapRegression.html"><a href="ChapRegression.html#the-scatter-plot"><i class="fa fa-check"></i><b>14.2.1</b> The Scatter Plot</a></li>
<li class="chapter" data-level="14.2.2" data-path="ChapRegression.html"><a href="ChapRegression.html#linear-equation"><i class="fa fa-check"></i><b>14.2.2</b> Linear Equation</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="ChapRegression.html"><a href="ChapRegression.html#linear-regression"><i class="fa fa-check"></i><b>14.3</b> Linear Regression</a><ul>
<li class="chapter" data-level="14.3.1" data-path="ChapRegression.html"><a href="ChapRegression.html#fitting-the-regression-line"><i class="fa fa-check"></i><b>14.3.1</b> Fitting the Regression Line</a></li>
<li class="chapter" data-level="14.3.2" data-path="ChapRegression.html"><a href="ChapRegression.html#subsec:Inference"><i class="fa fa-check"></i><b>14.3.2</b> Inference</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="ChapRegression.html"><a href="ChapRegression.html#r-squared-and-the-variance-of-residuals"><i class="fa fa-check"></i><b>14.4</b> R-squared and the Variance of Residuals</a></li>
<li class="chapter" data-level="14.5" data-path="ChapRegression.html"><a href="ChapRegression.html#exercises-9"><i class="fa fa-check"></i><b>14.5</b> Exercises</a></li>
<li class="chapter" data-level="14.6" data-path="ChapRegression.html"><a href="ChapRegression.html#summary-12"><i class="fa fa-check"></i><b>14.6</b> Summary</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the Forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ChapLogistic.html"><a href="ChapLogistic.html"><i class="fa fa-check"></i><b>15</b> A Bernoulli Response</a><ul>
<li class="chapter" data-level="15.1" data-path="ChapLogistic.html"><a href="ChapLogistic.html#student-learning-objectives-9"><i class="fa fa-check"></i><b>15.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="15.2" data-path="ChapLogistic.html"><a href="ChapLogistic.html#comparing-sample-proportions"><i class="fa fa-check"></i><b>15.2</b> Comparing Sample Proportions</a></li>
<li class="chapter" data-level="15.3" data-path="ChapLogistic.html"><a href="ChapLogistic.html#logistic-regression"><i class="fa fa-check"></i><b>15.3</b> Logistic Regression</a></li>
<li class="chapter" data-level="15.4" data-path="ChapLogistic.html"><a href="ChapLogistic.html#exercises-10"><i class="fa fa-check"></i><b>15.4</b> Exercises</a><ul>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#glossary"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="ChapIntroR.html"><a href="ChapIntroR.html#discuss-in-the-forum"><i class="fa fa-check"></i>Discuss in the forum</a></li>
<li class="chapter" data-level="" data-path="ChapDescriptiveStat.html"><a href="ChapDescriptiveStat.html#formulas"><i class="fa fa-check"></i>Formulas:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html"><i class="fa fa-check"></i><b>16</b> Case Studies</a><ul>
<li class="chapter" data-level="16.1" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#student-learning-objective-5"><i class="fa fa-check"></i><b>16.1</b> Student Learning Objective</a></li>
<li class="chapter" data-level="16.2" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#a-review"><i class="fa fa-check"></i><b>16.2</b> A Review</a></li>
<li class="chapter" data-level="16.3" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#case-studies"><i class="fa fa-check"></i><b>16.3</b> Case Studies</a><ul>
<li class="chapter" data-level="16.3.1" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#physicians-reactions-to-the-size-of-a-patient"><i class="fa fa-check"></i><b>16.3.1</b> Physicians’ Reactions to the Size of a Patient</a></li>
<li class="chapter" data-level="16.3.2" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#physical-strength-and-job-performance"><i class="fa fa-check"></i><b>16.3.2</b> Physical Strength and Job Performance</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#summary-13"><i class="fa fa-check"></i><b>16.4</b> Summary</a><ul>
<li class="chapter" data-level="16.4.1" data-path="ChapCaseStudies.html"><a href="ChapCaseStudies.html#concluding-remarks"><i class="fa fa-check"></i><b>16.4.1</b> Concluding Remarks</a></li>
<li class="chapter" data-level="16.4.2" data-path="ChapProbability.html"><a href="ChapProbability.html#discussion-in-the-forum"><i class="fa fa-check"></i><b>16.4.2</b> Discussion in the Forum</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i>Exercise Solutions</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-1"><i class="fa fa-check"></i>Chapter 1</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-1.1"><i class="fa fa-check"></i>Exercise 1.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-1.2"><i class="fa fa-check"></i>Exercise 1.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-2"><i class="fa fa-check"></i>Chapter 2</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-2.1"><i class="fa fa-check"></i>Exercise 2.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-2.2"><i class="fa fa-check"></i>Exercise 2.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-3"><i class="fa fa-check"></i>Chapter 3</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-3.1"><i class="fa fa-check"></i>Exercise 3.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-3.2"><i class="fa fa-check"></i>Exercise 3.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-4"><i class="fa fa-check"></i>Chapter 4</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-4.1"><i class="fa fa-check"></i>Exercise 4.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-4.2"><i class="fa fa-check"></i>Exercise 4.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-5"><i class="fa fa-check"></i>Chapter 5</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-5.1"><i class="fa fa-check"></i>Exercise 5.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-5.2"><i class="fa fa-check"></i>Exercise 5.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-6"><i class="fa fa-check"></i>Chapter 6</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-6.1"><i class="fa fa-check"></i>Exercise 6.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-6.2"><i class="fa fa-check"></i>Exercise 6.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-7"><i class="fa fa-check"></i>Chapter 7</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-7.1"><i class="fa fa-check"></i>Exercise 7.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-7.2"><i class="fa fa-check"></i>Exercise 7.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-9"><i class="fa fa-check"></i>Chapter 9</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-9.1"><i class="fa fa-check"></i>Exercise 9.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-9.2"><i class="fa fa-check"></i>Exercise 9.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-10"><i class="fa fa-check"></i>Chapter 10</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-10.1"><i class="fa fa-check"></i>Exercise 10.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-10.2"><i class="fa fa-check"></i>Exercise 10.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-11"><i class="fa fa-check"></i>Chapter 11</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-11.1"><i class="fa fa-check"></i>Exercise 11.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-11.2"><i class="fa fa-check"></i>Exercise 11.2</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-11.3"><i class="fa fa-check"></i>Exercise 11.3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-12"><i class="fa fa-check"></i>Chapter 12</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-12.1"><i class="fa fa-check"></i>Exercise 12.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-12.2"><i class="fa fa-check"></i>Exercise 12.2</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-12.3"><i class="fa fa-check"></i>Exercise 12.3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-13"><i class="fa fa-check"></i>Chapter 13</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-13.1"><i class="fa fa-check"></i>Exercise 13.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-13.2"><i class="fa fa-check"></i>Exercise 13.2</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-13.3"><i class="fa fa-check"></i>Exercise 13.3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-14"><i class="fa fa-check"></i>Chapter 14</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.1"><i class="fa fa-check"></i>Exercise 14.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.2"><i class="fa fa-check"></i>Exercise 14.2</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.3"><i class="fa fa-check"></i>Exercise 14.3</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.4"><i class="fa fa-check"></i>Exercise 14.4</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.5"><i class="fa fa-check"></i>Exercise 14.5</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-14.6"><i class="fa fa-check"></i>Exercise 14.6</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chapter-15"><i class="fa fa-check"></i>Chapter 15</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-15.1"><i class="fa fa-check"></i>Exercise 15.1</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-15.2"><i class="fa fa-check"></i>Exercise 15.2</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistical Thinking</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ChapTwoSamp" class="section level1">
<h1><span class="header-section-number">Chapter 13</span> Comparing Two Samples</h1>
<div id="student-learning-objectives-7" class="section level2">
<h2><span class="header-section-number">13.1</span> Student Learning Objectives</h2>
<p>The next 3 chapters deal with the statistical inference associated with the relation between two variables. The relation corresponds to the effect of one variable on the distribution of the other. The variable whose distribution is being investigated is called the <em>response</em>. The variable which may have an effect on the distribution of the response is called the <em>explanatory variable</em>.</p>
<p>In this section we consider the case where the explanatory variable is a factor with two levels. This factor splits the sample into two sub-samples. The statistical inference compares between the distributions of the response variable in the two sub-samples. The statistical inference involves point estimation, confidence intervals, and hypothesis testing. <code>R</code> functions may be used in order to carry out the statistical inference. By the end of this chapter, the student should be able to:</p>
<ul>
<li><p>Define estimators, confidence intervals, and tests for comparing the distribution of a numerical response between two sub-populations.</p></li>
<li><p>Apply the function “<code>t.test</code>” in order to investigate the difference between the expectations of the response variable in the two sub-samples.</p></li>
<li><p>Apply the function “<code>var.test</code>” in order to investigate the ratio between the variances of the response variable in the two sub-samples.</p></li>
</ul>
</div>
<div id="comparing-two-distributions" class="section level2">
<h2><span class="header-section-number">13.2</span> Comparing Two Distributions</h2>
<p>Up until this point in the book we have been considering tools for the investigation of the characteristics of the distribution of a single measurement. In most applications, however, one is more interested in inference regarding the relationships between several measurements. In particular, one may want to understand how the outcome of one measurement effects the outcome of another measurement.</p>
<p>A common form of a mathematical relation between two variables is when one of the variables is a function of the other. When such a relation holds then the value of the first variably is determined by the value of the second. However, in the statistical context relations between variables are more complex. Typically, a statistical relation between variables does not make one a direct function of the other. Instead, the <em>distribution</em> of values of one of the variables is affected by the value of the other variable. For a given value of the second variable the first variable may have one distribution, but for a different value of the second variable the distribution of the first variable may be different. In statistical terminology the second variable in this setting is called an <em>explanatory variable</em> and the first variable, with a distribution affected by the second variable, is called the <em>response</em>.</p>
<p>As an illustration of the relation between the response and the explanatory variable consider the following example. In a clinical trial, which is a precondition for the marketing of a new medical treatment, a group of patients is randomly divided into a <em>treatment</em> and a <em>control</em> sub-groups. The new treatment is anonymously administered to the treatment sub-group. At the same time, the patients in the control sub-group obtain the currently standard treatment. The new treatment passes the trial and is approved for marketing by the Health Authorities only if the response to the medical intervention is better for the treatment sub-group than it is for the control sub-group. This treatment-control experimental design, in which a response is measured under two experimental conditions, is used in many scientific and industrial settings.</p>
<p>In the example of a clinical trial one may identify two variables. One variable measures the response to the medical intervention for each patient that participated in the trial. This variable is the response variable, the distribution of which one seeks to investigate. The other variable indicates to which sub-group, treatment or control, each patient belongs. This variable is the explanatory variable. In the setting of a clinical trial the explanatory variable is a factor with two levels, “treatment” and “control”, that splits the sample into two sub-samples. The statistical inference compares the distribution of the response variable among the patients in the treatment sub-sample to the distribution of the response among the patients in the control sub-group.</p>
<p>The analysis of experimental settings such as the treatment-control trial ia a special case that involves the investigation of the effect an explanatory variable may have on the response variable. In this special case the explanatory variable is a factor with two distinct levels. Each level of the factor is associate with a sub-sample, either treatment or control. The analysis seeks to compare the distribution of the response in one sub-sample with the distribution in the other sub-sample. If the response is a numeric measurement then the analysis may take the form of comparing the response’s expectation in one sub-group to the expectation in the other. Alternatively, the analysis may involve comparing the variance. In a different case, if the response is the indicator of the occurrence of an event then the analysis may compare two probabilities, the probability of the event in the treatment group to the probability of the same event in the control group.</p>
<p>In this chapter we deal with statistical inference that corresponds to the comparison of the distribution of a numerical response variable between two sub-groups that are determined by a factor. The inference includes testing hypotheses, mainly the null hypothesis that the distribution of the response is the same in both subgroups versus the alternative hypothesis that the distribution is not the same. Another element in the inference is point estimation and confidence intervals of appropriate parameters.</p>
<p>In the next chapter we will consider the case where the explanatory variable is numeric and in the subsequent chapter we describe the inference that is used in the case that the response is the indicator of the occurrence of an event.</p>
</div>
<div id="sec:ComparingMeans" class="section level2">
<h2><span class="header-section-number">13.3</span> Comparing the Sample Means</h2>
<p>In this section we deal with the issue of statistical inference when comparing the expectation of the response variable in two sub-samples. The inference is used in order to address questions such as the equality of the two expectations to each other and, in the case they are not equal, the assessment of the difference between the expectations. For the first question one may use statistical hypothesis testing and for the assessment one may use point estimates and/or confidence intervals.</p>
<p>In the first subsection we provide an example of a test of the hypothesis that the expectations are equal. A confidence interval for the difference between expectations is given in the output of the report of the <span><code>R</code></span> function that applies the test. The second subsection considers the construction of the confidence interval and the third subsection deals with the theory behind the statistical test.</p>
<div id="an-example-of-a-comparison-of-means" class="section level3">
<h3><span class="header-section-number">13.3.1</span> An Example of a Comparison of Means</h3>
<p>In order to illustrate the statistical inference that compars two expectations let us return to an example that was considered in Chapter <a href="ChapTesting.html#ChapTesting">12</a>. The response of interest is the difference in miles-per-gallon between driving in highway conditions and driving in city conditions. This response is produced as the difference between the variable “<code>cars$highway.mpg</code>” and the variable “<code>cars$city.mpg</code>”. It is stored in the object “<code>dif.mpg</code>”, which is a numerical sequence:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cars &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;_data/cars.csv&quot;</span>)
dif.mpg &lt;-<span class="st"> </span>cars<span class="op">$</span>highway.mpg <span class="op">-</span><span class="st"> </span>cars<span class="op">$</span>city.mpg</code></pre></div>
<p>The object “<code>heavy</code>” was defined in the previous chapter as a sequence with logical components. A component had the value “<code>TRUE</code>” if the curb weight of the car type associated with this component was above the median level of 2,414 lb. The component obtained the value “<code>FALSE</code>” if the curb weight did not exceed that level. The logical sequence “<code>heavy</code>” was used in order to select the subsequences associated with each weight sub-group. Statistical inference was applied separately to each subsequence.</p>
<p>In the current analysis we want to examine directly the relation between the response variable “<code>dif.mpg</code>” and an explanatory factor variable “<code>heavy</code>”. In order to do so we redefine the variable “<code>heavy</code>” to be a factor:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">heavy &lt;-<span class="st"> </span><span class="kw">factor</span>(cars<span class="op">$</span>curb.weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">2414</span>)</code></pre></div>
<p>The variable “<code>curb.weight</code>” is numeric and the expression “<code>cars$curb.weight &gt; 2414</code>” produces a sequence with logical “<code>TRUE</code>” or “<code>FALSE</code>” components. This sequence is not a factor. In order to produce a factor we apply the function “<code>factor</code>” to the sequence. The function “<code>factor</code>” transforms its input into a factor. Specifically, the application of this function to a sequence with logical components produces a factor with two levels that are given the names “<code>TRUE</code>” and “<code>FALSE</code>”<a href="#fn62" class="footnoteRef" id="fnref62"><sup>62</sup></a>.</p>
<p>We want to examine the relation between the response variable “<code>dif.mpg</code>” and the explanatory factor “<code>heavy</code>”. Towards that end we produce a plot of the relation with the function “<code>plot</code>” and test for the equality of the expectations of the response with the function “<code>t.test</code>”. First the plot:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(dif.mpg<span class="op">~</span>heavy)</code></pre></div>
<p><img src="statthink_files/figure-html/unnamed-chunk-194-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Observe that the figure contains two box plots, one associated with the level “<code>FALSE</code>” of the explanatory factor and the other with the level “<code>TRUE</code>” of that factor. The box plots describe the distribution of the response variable for each level of the explanatory factor. Overall, the distribution of the response for heavier cars (cars associated with the level “<code>TRUE</code>”) tends to obtain smaller values than the distribution of the response for lighter cars (cars associated with the level “<code>FALSE</code>”).</p>
<p>The input to the function “<code>plot</code>” is a <em>formula</em> expression of the form: “<em>response<span class="math inline">\(\;\tilde{}\;\)</span>explanatory.variable</em>”. A formula identifies the role of variables. The variable to the left of the tilde character (<span class="math inline">\(\;\tilde{}\;\)</span>) in a formula is the response and the variable to the right is the explanatory variable. In the current case the variable “<code>dif.mpg</code>” is the response and the variable “<code>heavy</code>” is the explanatory variable.</p>
<p>Let us use a formal test in order to negate the hypothesis that the expectation of the response for the two weight groups is the same. The test is provided by the application of the function “<code>t.test</code>” to the formula “<code>dif.mpg\;\tilde{}\;heavy</code>”:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(dif.mpg<span class="op">~</span>heavy)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  dif.mpg by heavy
## t = 2.42552, df = 191.561, p-value = 0.016214
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.10291504 0.99893152
## sample estimates:
## mean in group FALSE  mean in group TRUE 
##           5.8058252           5.2549020</code></pre>
<p>The function “<code>t.test</code>”, when applied to a formula that describes the relation between a numeric response and a explanatory factor with two level, produces a special form of a <span class="math inline">\(t\)</span>-test that is called the <em>Welch Two Sample <span class="math inline">\(t\)</span>-test</em>. The statistical model associated with this test assumes the present of two independent sub-samples, each associated with a level of the explanatory variable. The relevant parameters for this model are the two expectations and the two variances associated with the sub-samples.</p>
<p>The hypotheses tested in the context of the Welch test are formulated in terms of the difference between the expectation of the first sub-sample and the expectation of the second sub-sample. In the default application of the test the null hypothesis is that the difference is equal to 0 (or, equivalently, that the expectations are equal to each other). The alternative is that the difference is not equal to 0 (hence, the expectations differ).</p>
<p>The test is conducted with the aid of a test statistic. The computed value of the test statistic in this example is “<code>t = 2.4255</code>”. Under the null hypothesis the distribution of the test statistic is (approximately) equal to the <span class="math inline">\(t\)</span>-distribution on “<code>df = 191.561</code>” degrees of freedom. The resulting <span class="math inline">\(p\)</span>-value is “<code>p-value = 0.01621</code>”. Since the computed <span class="math inline">\(p\)</span>-value is less than 0.05 we reject the null hypothesis with a significance level of 5% and declare that the expectations are not equal to each other.</p>
<p>The bottom part of the report presents points estimates and a confidence interval. The point estimates of the two expectations are the sub-samples averages. The estimated value of the expected difference in miles-per-gallon for lighter cars is 5.805825, which is the average of the measurements associated with the level “<code>FALSE</code>”. The estimated value of the expected difference for heavier cars is 5.254902, the average of measurements associated with the level “<code>TRUE</code>”.</p>
<p>The point estimate for the difference between the two expectations is the difference between the two sample averages: <span class="math inline">\(5.805825 - 5.254902 = 0.550923\)</span>. A confidence interval for the <em>difference</em> between the expectations is reported under the title “<code>95 percent confidence interval:</code>”. The computed value of the confidence interval is <span class="math inline">\([0.1029150, 0.9989315]\)</span>.</p>
<p>In the rest of this section we describe the theory behind the construction of the confidence interval and the statistical test.</p>
</div>
<div id="confidence-interval-for-the-difference" class="section level3">
<h3><span class="header-section-number">13.3.2</span> Confidence Interval for the Difference</h3>
<p>Consider the statistical model that is used for the construction of the confidence interval. The main issue is that the model actually deals with two populations rather than one population. In previous theoretical discussions we assumed the presence of a single population and a measurement taken for the members of this population. When the measurement was considered as a random variable it was denoted by a capital Latin letter such as <span class="math inline">\(X\)</span>. Of concern were characteristics of the distribution of <span class="math inline">\(X\)</span> such as <span class="math inline">\(E(X)\)</span>, the expectation of <span class="math inline">\(X\)</span>, and <span class="math inline">\(V(X)\)</span>, the variance.</p>
<p>In the current investigation two populations are considered. One population is the sub-population associated with the first level of the factor and the other population is associated with the second level. The measurement is taken for the members of both sub-populations. However, the measurement involves two random variables, one associated with the first sub-population and the other associated with the second sub-population. Moreover, the distribution of the measurement for one population may differ from the distribution for the other population. We denote the random variable associated with the first sub-population by <span class="math inline">\(X_a\)</span> and the one associated with the other sub-population by <span class="math inline">\(X_b\)</span>.</p>
<p>Consider the example in which the measurement is the difference in miles-per-gallon between highway and city driving conditions. In this example <span class="math inline">\(X_a\)</span> is the measurement for cars with curb weight up to 2,414 lb and <span class="math inline">\(X_b\)</span> is the same measurement for cars with curb weight above that threshold.</p>
<p>The random variables <span class="math inline">\(X_a\)</span> and <span class="math inline">\(X_b\)</span> may have different distributions. Consequently, the characteristics of their distributions may also vary. Denote by <span class="math inline">\(E(X_a)\)</span> and <span class="math inline">\(E(X_b)\)</span> the expectations of the first and second random variable, respectively. Likewise, <span class="math inline">\(V(X_a)\)</span> and <span class="math inline">\(V(X_b)\)</span> are the variances of the two random variables. These expectations and variances are subjects of the statistical inference.</p>
<p>The sample itself may also be divided into two sub-samples according to the sub-population each observation originated from. In the example, one sub-sample is associated with the lighter car types and the other sub-sample with the heavier ones. These sub-samples can be used in order to make inference with respect to the parameters of <span class="math inline">\(X_a\)</span> and <span class="math inline">\(X_b\)</span>, respectively. For example, the average of the observations from first sub-sample, <span class="math inline">\(\bar X_a\)</span>, can serve as the estimator of the of the expectation <span class="math inline">\(E(X_a)\)</span> and the second sub-sample‘s average <span class="math inline">\(\bar X_b\)</span> may be used in order to estimate <span class="math inline">\(E(X_b)\)</span>.</p>
<p>Our goal in this section is to construct a confidence interval for the difference in expectations <span class="math inline">\(E(X_a)-E(X_b)\)</span>. A natural estimator for this difference in expectations is the difference in averages <span class="math inline">\(\bar X_a- \bar X_b\)</span>. The average difference will also serve as the basis for the construction of a confidence interval.</p>
<p>Recall that the construction of the confidence interval for a signal expectation was based on the sample average <span class="math inline">\(\bar X\)</span>. We exploited the fact that the distribution of <span class="math inline">\(Z = (\bar X - E(X)/\sqrt{V(X)/n}\)</span>, the standardized sample average, is approximately standard Normal. From this Normal approximation we obtained an approximate 0.95 probability for the event</p>
<p><span class="math display">\[\big\{-1.96 \cdot \sqrt{V(X)/n} \leq \bar X - E(X) \leq 1.96 \cdot \sqrt{V(X)/n}\big\}\;,\]</span> where <span class="math inline">\(1.96 = \mbox{\texttt{qnorm(0.975)}}\)</span> is the 0.975-percentile of the standard Normal distribution<a href="#fn63" class="footnoteRef" id="fnref63"><sup>63</sup></a>. Substituting the estimator <span class="math inline">\(S\)</span> for the unknown variance of the measurement and rewriting the event in a format that puts the expectation <span class="math inline">\(E(X)\)</span> in the center, between two boundaries, produced the confidence interval:</p>
<p><span class="math display">\[\bar X \pm 1.96 \cdot S/\sqrt{n}\;.\]</span></p>
<p>Similar considerations can be used in the construction of a confidence interval for the difference between expectations on the basis of the difference between sub-sample averages. The deviation <span class="math inline">\(\{\bar X_a- \bar X_b\} - \{E(X_a)- E(X_b)\}\)</span> between the difference of the averages and the difference of the expectations that they estimate can be standardized. By the Central Limit Theorem one may obtain that the distribution of the standardized deviation is approximately standard Normal.</p>
<p>Standardization is obtained by dividing by the standard deviation of the estimator. In the current setting the estimator is the difference between the averages. The variance of the difference is given by</p>
<p><span class="math display">\[V(\bar X_a- \bar X_b) = V(\bar X_a) + V(\bar X_b) = \frac{V(X_a)}{n_a} + \frac{V(X_b)}{n_b}\;,\]</span> where <span class="math inline">\(n_a\)</span> is the size of the sub-sample that produces the sample average <span class="math inline">\(\bar X_a\)</span> and <span class="math inline">\(n_b\)</span> is the size of the sub-sample that produces the sample average <span class="math inline">\(\bar X_b\)</span>. Observe that both <span class="math inline">\(\bar X_a\)</span> and <span class="math inline">\(\bar X_b\)</span> contribute to the variability of the difference. The total variability is the sum of the two contributions<a href="#fn64" class="footnoteRef" id="fnref64"><sup>64</sup></a>. Finally, we use the fact that the variance of the sample average is equal to he variance of a single measurement divided by the sample size. This fact is used for both averages in order to obtain a representation of the variance of the estimator in terms of the variances of the measurement in the two sub-population and the sizes of the two sub-samples.</p>
<p>The standardized deviation takes the form:</p>
<p><span class="math display">\[Z = \frac{\bar X_a- \bar X_b - \{E(X_a)- E(X_b)\}}{\sqrt{V(X_a)/n_a +V(X_b)/n_b}}\;.\]</span> When both sample sizes <span class="math inline">\(n_a\)</span> and <span class="math inline">\(n_b\)</span> are large then the distribution of <span class="math inline">\(Z\)</span> is approximately standard Normal. As a corollary from the Normal approximation one gets that <span class="math inline">\(P(-1.96 \leq Z \leq 1.96) \approx 0.95\)</span>.</p>
<p>The values of variances <span class="math inline">\(V(X_a)\)</span> and <span class="math inline">\(V(X_b)\)</span> that appear in the definition of <span class="math inline">\(Z\)</span> are unknown. However, these values can be estimated using the sub-samples variances <span class="math inline">\(S_a^2\)</span> and <span class="math inline">\(S_b^2\)</span>. When the size of both sub-samples is large then these estimators will produce good approximations of the unknown variances:</p>
<p><span class="math display">\[V(X_a) \approx S_a^2,\; V(X_b) \approx S_b^2\quad \Longrightarrow \quad\frac{V(X_a)}{n_a} + \frac{V(X_b)}{n_b} \approx  \frac{S_a^2}{n_a} + \frac{S_b^2}{n_b}\;.\]</span></p>
<p>The event <span class="math inline">\(\{-1.96 \leq Z \leq 1.96\}\)</span> may be approximated by the event:</p>
<p><span class="math display">\[\Bigg\{-1.96 \cdot \sqrt{\frac{S_a^2}{n_a} + \frac{S_b^2}{n_b}} \leq \bar X_a- \bar X_b - \{E(X_a)- E(X_b)\} \leq 1.96 \cdot \sqrt{\frac{S_a^2}{n_a} + \frac{S_b^2}{n_b}}\Bigg\}\;,\]</span> The approximation results from the use of the sub-sample variances as a substitute for the unknown variances of the measurement in the two sub-populations. When the two sample sizes <span class="math inline">\(n_a\)</span> and <span class="math inline">\(n_b\)</span> are large then the probability of the given event will also be approximately equal to 0.95.</p>
<p>Finally, reexpressing the least event in a format that puts the parameter <span class="math inline">\(E(X_a)- E(X_b)\)</span> in the center will produce the confidence interval with boundaries of the form:</p>
<p><span class="math display">\[\bar X_a- \bar X_b \pm 1.96 \cdot \sqrt{S_a^2/n_a + S_b^2/n_b}\]</span></p>
<p>In order to illustrate the computations that are involved in the construction of a confidence interval for the difference between two expectations let us return to the example of difference in miles-per-gallon for lighter and for heavier cars. Compute the two sample sizes, sample averages, and sample variances:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(heavy)</code></pre></div>
<pre><code>## heavy
## FALSE  TRUE 
##   103   102</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(dif.mpg,heavy,mean)</code></pre></div>
<pre><code>##     FALSE      TRUE 
## 5.8058252 5.2549020</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(dif.mpg,heavy,var)</code></pre></div>
<pre><code>##     FALSE      TRUE 
## 2.0207500 3.2611143</code></pre>
<p>Observe that there 103 lighter cars and 102 heavier ones. These counts were obtained by the application of the function “<code>table</code>” to the factor “<code>heavy</code>”. The lighter cars are associated with the level “<code>FALSE</code>” and heavier cars are associated with the level “<code>TRUE</code>”.</p>
<p>The average difference in miles-per-gallon for lighter cars is 5.805825 and the variance is 2.020750. The average difference in miles-per-gallon for heavier cars is 5.254902 and the variance is 3.261114. These quantities were obtained by the application of the functions “<code>mean</code>” or “<code>var</code>” to the values of the variable “<code>dif.mpg</code>” that are associated with each level of the factor “<code>heavy</code>”. The application was carried out using the function “<code>tapply</code>”.</p>
<p>The computed values of the means are equal to the vales reported in the output of the application of the function “<code>t.test</code>” to the formula “<code>dif.mpg\;\tilde{}\;heavy</code>”. The difference between the averages is <span class="math inline">\(\bar x_a - \bar x_b = 5.805825 - 5.254902 = 0.550923\)</span>. This value is the center of the confidence interval. The estimate of the standard deviation of the difference in averages is:</p>
<p><span class="math display">\[\sqrt{s_a^2/n_a + s_b^2/n_b} = \sqrt{2.020750/103 + 3.261114/102} = 0.227135\;.\]</span> Therefore, the confidence interval for the difference in expectations is</p>
<p><span class="math display">\[\bar x_a- \bar x_b \pm 1.96 \cdot \sqrt{\frac{s_a^2}{n_a} + \frac{s_b^2}{n_b}} = 0.550923 \pm 1.96 \cdot 0.227135 = [0.1057384,0.9961076]\;,\]</span> which is (essentially) the confidence interval that is presented in the report<a href="#fn65" class="footnoteRef" id="fnref65"><sup>65</sup></a>.</p>
</div>
<div id="the-t-test-for-two-means" class="section level3">
<h3><span class="header-section-number">13.3.3</span> The t-Test for Two Means</h3>
<p>The statistical model that involves two sub-populations may be considered also in the context of hypothesis testing. Hypotheses can be formulated regarding the relations between the parameters of the model. These hypotheses can be tested using the data. For example, in the current application of the <span class="math inline">\(t\)</span>-test, the null hypothesis is <span class="math inline">\(H_0: E(X_a) = E(X_b)\)</span> and the alternative hypothesis is <span class="math inline">\(H_1: E(X_a) \not= E(X_b)\)</span>. In this subsection we explain the theory behind this test.</p>
<p>Recall that the construction of a statistical test included the definition of a test statistic and the determination of a rejection region. The null hypothesis is rejected if, and only if, the test statistic obtains a value in the rejection region. The determination of the rejection region is based on the sampling distribution of the test statistic under the null hypothesis. The significance level of the test is the probability of rejecting the null hypothesis (i.e., the probability that the test statistic obtains a value in the rejection region) when the null hypothesis is correct (the distribution of the test statistic is the distribution under the null hypothesis). The significance level of the test is set at a given value, say 5%, thereby restricting the size of the rejection region.</p>
<p>In the previous chapter we consider the case where there is one population. For review, consider testing the hypothesis that the expectation of the measurement is equal to zero (<span class="math inline">\(H_0: E(X) = 0\)</span>) against the alternative hypothesis that it is not (<span class="math inline">\(H_1: E(X) \not = 0\)</span>). A sample of size <span class="math inline">\(n\)</span> is obtained from this population. Based on the sample one may compute a test statistic:</p>
<p><span class="math display">\[T = \frac{\bar X - 0}{S/\sqrt{n}} = \frac{\bar X}{S/\sqrt{n}}\;,\]</span> where <span class="math inline">\(\bar X\)</span> is the sample average and <span class="math inline">\(S\)</span> is the sample standard deviation. The rejection region of this test is <span class="math inline">\(\{|T| &gt; \mbox{\texttt{qt(0.975,n-1)}}\}\)</span>, for “<code>qt(0.975,n-1)</code>” the 0.975-percentile of the <span class="math inline">\(t\)</span>-distribution on <span class="math inline">\(n-1\)</span> degrees of freedom.</p>
<p>Alternatively, one may compute the <span class="math inline">\(p\)</span>-value and reject the null hypothesis if the <span class="math inline">\(p\)</span>-value is less than 0.05. The <span class="math inline">\(p\)</span>-value in this case is equal to <span class="math inline">\(P(|T| &gt; |t|)\)</span>, where <span class="math inline">\(t\)</span> is the computed value of the test statistic. The distribution of <span class="math inline">\(T\)</span> is the <span class="math inline">\(t\)</span>-distribution of <span class="math inline">\(n-1\)</span> degrees of freedom.</p>
<p>A similar approach can be used in the situation where two sub-population are involved and one wants to test the null hypothesis that the expectations are equal versus the alternative hypothesis that they are not. The null hypothesis can be written in the form <span class="math inline">\(H_0:E(X_a) - E(X_b) = 0\)</span> with the alternative hypothesis given as <span class="math inline">\(H_1:E(X_a) - E(X_b) \not = 0\)</span>.</p>
<p>It is natural to base the test static on the difference between sub-samples averages <span class="math inline">\(\bar X_a - \bar X_b\)</span>. The <span class="math inline">\(T\)</span> statistic is the ratio between the deviation of the estimator from the null value of the parameter, divided by the (estimated) standard deviation of the estimator. In the current setting the estimator is difference in sub-samples averages <span class="math inline">\(\bar X_a - \bar X_b\)</span>, the null value of the parameter, the difference between the expectations, is 0, and the (estimated) standard deviation of the estimator is <span class="math inline">\(\sqrt{S_a^2/n_a + S_b^2/n_b}\)</span>. It turns out that the test statistic in the current setting is:</p>
<p><span class="math display">\[T = \frac{\bar X_a - \bar X_b - 0}{ \sqrt{S_a^2/n_a + S^2_b/n_b}} = \frac{\bar X_a - \bar X_b}{ \sqrt{S_a^2/n_a + S^2_b/n_b}}\;.\]</span></p>
<p>Consider as a measurement the difference in miles-per-gallon. Define the sub-population <span class="math inline">\(a\)</span> to the lighter cars and the sub-population <span class="math inline">\(b\)</span> to be the heavier cars. Recall that the sub-sample sizes are <span class="math inline">\(n_a =103\)</span> and <span class="math inline">\(n_b=102\)</span>. Also, the sub-sample averages are <span class="math inline">\(\bar x_a = 5.805825\)</span> and <span class="math inline">\(\bar x_b =5.254902\)</span>, and the sub-sample variances are <span class="math inline">\(s^2_a = 2.020750\)</span> and <span class="math inline">\(s_b^2 = 5.254902\)</span>.</p>
<p>In order to calculate the observed value of the test statistic we use once more the fact that the difference between the averages is <span class="math inline">\(\bar x_a - \bar x_b = 5.805825 - 5.254902 = 0.550923\)</span> and the estimated value of the standard deviation of the sub-samples average difference is:</p>
<p><span class="math display">\[\sqrt{s_a^2/n_a + s_b^2/n_b} = \sqrt{2.020750/103 + 3.261114/102} = 0.227135\;.\]</span> It follows that the observed value of the <span class="math inline">\(T\)</span> statistic is</p>
<p><span class="math display">\[t = \frac{\bar x_a - \bar x_b}{\sqrt{s_a^2/n_a + s_b^2/n_b}} = \frac{0.550923}{0.227135} = 2.425531\;,\]</span> which, after rounding up, is equal to the value presented in the report that was produced by the function “<code>t.test</code>”.</p>
<p>The <span class="math inline">\(p\)</span>-value is computed as the probability of obtaining values of the test statistic more extreme than the value that was obtained in our data. The computation is carried out under the assumptions of the null hypothesis. The limit distribution of the <span class="math inline">\(T\)</span> statistic, when both sub-sample sizes <span class="math inline">\(n_a\)</span> and <span class="math inline">\(n_b\)</span> are large, is standard Normal. In the case when the measurements are Normally distributed then a refined approximation of the distribution of the statistic is the <span class="math inline">\(t\)</span>-distribution. Both the standard Normal and the <span class="math inline">\(t\)</span>-distribution are symmetric about the origin.</p>
<p>The probability of obtaining a value in either tails for a symmetric distribution is equal to twice the probability of obtaining a value in the upper tail:</p>
<p><span class="math display">\[P( |T| &gt; 2.4255) = 2 \times P( T &gt; 2.4255) =  2 \times \big [1 - P( T \leq  2.4255)\big ]\;.\]</span></p>
<p>The function “<code>t.test</code>” computes the <span class="math inline">\(p\)</span>-value using the <span class="math inline">\(t\)</span>-distribution. For the current data, the number of degrees of freedom that are used in this approximation<a href="#fn66" class="footnoteRef" id="fnref66"><sup>66</sup></a> is <code>df</code> = 191.561. When we apply the function “<code>pt</code>” for the computation of the cumulative probability of the <span class="math inline">\(t\)</span>-distribution we get:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span><span class="kw">pt</span>(<span class="fl">2.4255</span>,<span class="fl">191.561</span>))</code></pre></div>
<pre><code>## [1] 0.016214576</code></pre>
<p>which (after rounding) is equal to the reported <span class="math inline">\(p\)</span>-value of 0.01621. This <span class="math inline">\(p\)</span>-value is less than 0.05, hence the null hypothesis is rejected in favor of the alternative hypothesis that assumes an effect of the weight on the expectation.</p>
</div>
</div>
<div id="comparing-sample-variances" class="section level2">
<h2><span class="header-section-number">13.4</span> Comparing Sample Variances</h2>
<p>In the previous section we discussed inference associated with the comparison of the expectations of a numerical measurement between two sub-population. Inference included the construction of a confidence interval for the difference between expectations and the testing of the hypothesis that the expectations are equal to each other.</p>
<p>In this section we consider a comparisons between variances of the measurement in the two sub-populations. For this inference we consider the ratio between estimators of the variances and introduce a new distribution, the <span class="math inline">\(F\)</span>-distribution, that is associated with this ratio.</p>
<p>Assume, again, the presence of two sub-populations, denoted <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. A numerical measurement is taken over a sample. The sample can be divided into two sub-samples according to the sub-population of origin. In the previous section we were interested in inference regarding the relation between the expectations of the measurement in the two sub-populations. Here we are concerned with the comparison of the variances.</p>
<p>Specifically, let <span class="math inline">\(X_a\)</span> be the measurement at the first sub-population and let <span class="math inline">\(X_b\)</span> be the measurement at the second sub-population. We want to compare <span class="math inline">\(V(X_a)\)</span>, the variance in the first sub-population, to <span class="math inline">\(V(X_b)\)</span>, the variance in the second sub-population. As the basis for the comparison we may use <span class="math inline">\(S_a^2\)</span> and <span class="math inline">\(S_b^2\)</span>, the sub-samples variances, which are computed from the observations in the first and the second sub-sample, respectively.</p>
<p>Consider the confidence interval for the ratio of the variances. In Chapter <a href="ChapConfidence.html#ChapConfidence">11</a> we discussed the construction of the confidence interval for the variance in a single sample. The derivation was based on the sample variance <span class="math inline">\(S^2\)</span> that serves as an estimator of the population variance <span class="math inline">\(V(X)\)</span>. In particular, the distribution of the random variable <span class="math inline">\((n-1)S^2/V(X)\)</span> was identified as the chi-square distribution on <span class="math inline">\(n-1\)</span> degrees of freedom<a href="#fn67" class="footnoteRef" id="fnref67"><sup>67</sup></a>. A confidence interval for the variance was obtained as a result of the identification of a central region in the chi-square distribution that contains a pre-subscribed probability<a href="#fn68" class="footnoteRef" id="fnref68"><sup>68</sup></a>.</p>
<p>In order to construct a confidence interval for the ratio of the variances we consider the random variable that is obtained as a ratio of the estimators of the variances:</p>
<p><span class="math display">\[\frac{S_a^2/V(X_a)}{S^2_b/V(X_b)} \sim F_{(n_a-1,n_b-1)}\;.\]</span> The distribution of this random variable is denoted the <span class="math inline">\(F\)</span>-distribution<a href="#fn69" class="footnoteRef" id="fnref69"><sup>69</sup></a>. This distribution is characterized by the number of degrees of freedom associated with the estimator of the variance at the numerator and by the number of degrees of freedom associated with the estimator of the variance at the denominator. The number of degrees of freedom associated with the estimation of each variance is the number of observation used for the computation of the estimator, minus 1. In the current setting the numbers of degrees of freedom are <span class="math inline">\(n_a-1\)</span> and <span class="math inline">\(n_b-1\)</span>, respectively.</p>
<p>The percentiles of the <span class="math inline">\(F\)</span>-distribution can be computed in <code>R</code> using the function “<code>qf</code>”. For example, the 0.025-percentile of the distribution for the ratio between sample variances of the response for two sub-samples is computed by the expression “<code>qf(0.025,dfa,dfb)</code>”, where <span class="math inline">\(\mbox{\texttt{dfa}} = n_a - 1\)</span> and <span class="math inline">\(\mbox{\texttt{dfb}} = n_b - 1\)</span>. Likewise, the 0.975-percentile is computed by the expression “<code>qf(0.975,dfa,dfb)</code>”. Between these two numbers lie 95% of the given <span class="math inline">\(F\)</span>-distribution. Consequently, the probability that the random variable <span class="math inline">\(\{S_a^2/V(X_a)\}/\{S_b^2/V(X_b)\}\)</span> obtains its values between these two percentiles is equal to 0.95:</p>
<p><span class="math display">\[\begin{aligned}
\lefteqn{\frac{S_a^2/V(X_a)}{S_b^2/V(X_b)} \sim F_{(n_a-1,n_b-1)} \quad \Longrightarrow }\\ &amp; P \big( \mbox{\texttt{qf(0.025,dfa,dfb)}} \leq  {\textstyle \frac{S_a^2/V(X_a)}{S_b^2/V(X_b)}}  \leq \mbox{\texttt{qf(0.975,dfa,dfb)}} \big) = 0.95\;.\end{aligned}\]</span></p>
<p>A confidence interval for the ratio between <span class="math inline">\(V(X_a)\)</span> and <span class="math inline">\(V(X_b)\)</span> is obtained by reformulation of the last event. In the reformulation, the ratio of the variances is placed in the center:</p>
<p><span class="math display">\[\Big\{\frac{S_a^2/S_b^2}{\mbox{\texttt{qf(0.975,dfa,fdb)}}} \leq  \frac{V(X_a)}{V(X_b)}  \leq \frac{S_a^2/S_b^2}{\mbox{\texttt{qf(0.025,dfa,dfb)}}}\Big\}\;.\]</span> This confidence interval has a significance level of 95%.</p>
<p>Next, consider testing hypotheses regarding the relation between the variances. Of particular interest is testing the equality of the variances. One may formulate the null hypothesis as <span class="math inline">\(H_0: V(X_a)/V(X_b) = 1\)</span> and test it against the alternative hypothesis <span class="math inline">\(H_1: V(X_a)/V(X_b) \not = 1\)</span>.</p>
<p>The statistic <span class="math inline">\(F = S_a^2/S_b^2\)</span> can used in order to test the given null hypothesis. Values of this statistic that are either much larger or much smaller than 1 are evidence against the null hypothesis and in favor of the alternative hypothesis. The sampling distribution, under that null hypothesis, of this statistic is the <span class="math inline">\(F_{(n_a-1,n_b-1)}\)</span> distribution. Consequently, the null hypothesis is rejected either if <span class="math inline">\(F &lt; \mbox{\texttt{qf(0.025,dfa,dfb)}}\)</span> or if <span class="math inline">\(F &gt;\mbox{\texttt{qf(0.975,dfa,dfb)}}\)</span>, where <span class="math inline">\(\mbox{\texttt{dfa}} = n_a - 1\)</span> and <span class="math inline">\(\mbox{\texttt{dfb}} = n_b - 1\)</span>. The significance level of this test is 5%.</p>
<p>Given an observed value of the statistic, the <span class="math inline">\(p\)</span>-value is computed as the significance level of the test which uses the observed value as the threshold. If the observed value <span class="math inline">\(f\)</span> is less than 1 then the <span class="math inline">\(p\)</span>-value is twice the probability of the lower tail: <span class="math inline">\(2\cdot P(F &lt; f)\)</span>. On the other hand, if <span class="math inline">\(f\)</span> is larger than 1 one takes twice the upper tail as the <span class="math inline">\(p\)</span>-value: <span class="math inline">\(2\cdot P(F &gt; f) = 2\cdot [1-P(F \leq f)]\)</span>. The null hypothesis is rejected with a significance level of 5% if the <span class="math inline">\(p\)</span>-value is less than 0.05.</p>
<p>In order to illustrate the inference that compares variances let us return to the variable “<code>dif.mpg</code>” and compare the variances associated with the two levels of the factor “<code>heavy</code>”. The analysis will include testing the hypothesis that the two variances are equal and an estimate and a confidence interval for their ratio.</p>
<p>The function “<code>var.test</code>” may be used in order to carry out the required tasks. The input to the function is a formula such “<code>dif.mpg\;\tilde{}\;heavy</code>”, with a numeric variable on the left and a factor with two levels on the right. The default application of the function to the formula produces the desired test and confidence interval:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var.test</span>(dif.mpg<span class="op">~</span>heavy)</code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  dif.mpg by heavy
## F = 0.61965, num df = 102, denom df = 101, p-value = 0.016626
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.41892003 0.91621258
## sample estimates:
## ratio of variances 
##         0.61965017</code></pre>
<p>Consider the report produced by the function. The observed value of the test statistic is “<code>F = 0.6197</code>”, and it is associated with the <span class="math inline">\(F\)</span>-distribution on “<code>num df = 102</code>” and “<code>denom df = 101</code>” degrees of freedom. The test statistic can be used in order to test the null hypothesis <span class="math inline">\(H_0: V(X_a)/V(X_b) = 1\)</span>, that states that the two variance are equal, against the alternative hypothesis that they are not. The <span class="math inline">\(p\)</span>-value for this test is “<code>p-value = 0.01663</code>”, which is less than 0.05. Consequently, the null hypothesis is rejected and the conclusion is that the two variances are significantly different from each other. The estimated ratio of variances, given at the bottom of the report, is 0.6196502. The confidence interval for the ratio is reported also and is equal to <span class="math inline">\([0.4189200, 0.9162126]\)</span>.</p>
<p>In order to relate the report to the theoretical discussion above let us recall that the sub-samples variances are <span class="math inline">\(s^2_a = 2.020750\)</span> and <span class="math inline">\(s_b^2 = 3.261114\)</span>. The sub-samples sizes are <span class="math inline">\(n_a = 103\)</span> and <span class="math inline">\(n_b = 102\)</span>, respectively. The observed value of the statistic is the ratio <span class="math inline">\(s_a^2/s_b^2 = 2.020750/3.261114 = 0.6196502\)</span>, which is the value that appears in the report. Notice that this is the estimate of the ration between the variances that is given at the bottom of the report.</p>
<p>The <span class="math inline">\(p\)</span>-value of the two-sided test is equal to twice the probability of the tail that is associated with the observed value of the test statistic as a threshold. The number of degrees of freedom is <span class="math inline">\(\mbox{\texttt{dfa}} = n_a - 1 = 102\)</span> and <span class="math inline">\(\mbox{\texttt{dfb}} = n_b - 1 = 101\)</span>. The observed value of the ratio test statistic is <span class="math inline">\(f = 0.6196502\)</span>. This value is less than one. Consequently, the probability <span class="math inline">\(P(F &lt; 0.6196502)\)</span> enters into the computation of the <span class="math inline">\(p\)</span>-value, which equals twice this probability:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span><span class="op">*</span><span class="kw">pf</span>(<span class="fl">0.6196502</span>,<span class="dv">102</span>,<span class="dv">101</span>)</code></pre></div>
<pre><code>## [1] 0.016626121</code></pre>
<p>Compare this value to the <span class="math inline">\(p\)</span>-value that appears in the report and see that, after rounding up, the two are the same.</p>
<p>For the confidence interval of the ratio compute the percentiles of the <span class="math inline">\(F\)</span> distribution:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qf</span>(<span class="fl">0.025</span>,<span class="dv">102</span>,<span class="dv">101</span>)</code></pre></div>
<pre><code>## [1] 0.67631702</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qf</span>(<span class="fl">0.975</span>,<span class="dv">102</span>,<span class="dv">101</span>)</code></pre></div>
<pre><code>## [1] 1.479161</code></pre>
<p>The confidence interval is equal to:</p>
<p><span class="math display">\[\begin{aligned}
\Big[\frac{s_a^2/s_b^2}{\mbox{\texttt{qf(0.975,102,101)}}} , \frac{s_a^2/s_b^2}{\mbox{\texttt{qf(0.025,102,101)}}}\Big] &amp;= \Big[\frac{0.6196502}{1.479161} , \frac{0.6196502}{0.676317}\Big]\\ &amp;= [0.4189200, 0.9162127]\;,\end{aligned}\]</span> which coincides with the reported interval.</p>
</div>
<div id="exercises-8" class="section level2">
<h2><span class="header-section-number">13.5</span> Exercises</h2>

<div class="exercise">
<p><span id="exr:unnamed-chunk-201" class="exercise"><strong>Exercise 13.1  </strong></span>In this exercise we would like to analyze the results of the trial that involves magnets as a treatment for pain. The trial is described in Question <span class="math display">\[ex:Inference.1\]</span>. The results of the trial are provided in the file “<code>magnets.csv</code>”.</p>
<p>Patients in this trail where randomly assigned to a treatment or to a control. The responses relevant for this analysis are either the variable “<code>change</code>”, which measures the difference in the score of pain reported by the patients before and after the treatment, or the variable “<code>score1</code>”, which measures the score of pain before a device is applied. The explanatory variable is the factor “<code>active</code>”. This factor has two levels, level “<code>1</code>” to indicate the application of an active magnet and level “<code>2</code>” to indicate the application of an inactive placebo.</p>
<p>In the following questions you are required to carry out tests of hypotheses. All tests should conducted at the 5% significance level:</p>
<ol style="list-style-type: decimal">
<li><p>Is there a significance difference between the treatment and the control groups in the expectation of the reported score of pain before the application of the device?</p></li>
<li><p>Is there a significance difference between the treatment and the control groups in the variance of the reported score of pain before the application of the device?</p></li>
<li><p>Is there a significance difference between the treatment and the control groups in the expectation of the change in score that resulted from the application of the device?</p></li>
<li>Is there a significance difference between the treatment and the control groups in the variance of the change in score that resulted from the application of the device?</li>
</ol>
</div>


<div class="exercise">
<p><span id="exr:unnamed-chunk-202" class="exercise"><strong>Exercise 13.2  </strong></span>It is assumed, when constructing the <span class="math inline">\(F\)</span>-test for equality of variances, that the measurements are Normally distributed. In this exercise we what to examine the robustness of the test to divergence from the assumption. You are required to compute the significance level of a two-sided <span class="math inline">\(F\)</span>-test of <span class="math inline">\(H_0:V(X_a)=V(X_b)\)</span> versus <span class="math inline">\(H_1: V(X_a)\not =V(X_b)\)</span>. Assume there are <span class="math inline">\(n_a=29\)</span> observations in one group and <span class="math inline">\(n_b = 21\)</span> observations in the other group. Use an <span class="math inline">\(F\)</span>-test with a nominal 5% significance level.</p>
<ol style="list-style-type: decimal">
<li><p>Consider the case where <span class="math inline">\(X \sim \mathrm{Normal}(4,4^2)\)</span>.</p></li>
<li>Consider the case where <span class="math inline">\(X \sim \mathrm{Exponential}(1/4)\)</span>.</li>
</ol>
</div>


<div class="exercise">
<p><span id="exr:unnamed-chunk-203" class="exercise"><strong>Exercise 13.3  </strong></span>The sample average in one sub-sample is <span class="math inline">\(\bar x_a = 124.3\)</span> and the sample standard deviation is <span class="math inline">\(s_a = 13.4\)</span>. The sample average in the second sub-sample is <span class="math inline">\(\bar x_b = 80.5\)</span> and the sample standard deviation is <span class="math inline">\(s_b = 16.7\)</span>. The size of the first sub-sample is <span class="math inline">\(n_a=15\)</span> and this is also the size of the second sub-sample. We are interested in the estimation of the ratio of variances <span class="math inline">\(V(X_a)/V(X_b)\)</span>.</p>
<ol style="list-style-type: decimal">
<li><p>Compute the estimate of parameter of interest.</p></li>
<li><p>Construct a confidence interval, with a confidence level of 95%, to the value of the parameter of interest.</p></li>
<li>It is discovered that the size of each of the sub-samples is actually equal to 150, and no to 15 (but the values of the other quantities are unchanged). What is the corrected estimate? What is the corrected confidence interval?</li>
</ol>
</div>

</div>
<div id="summary-11" class="section level2">
<h2><span class="header-section-number">13.6</span> Summary</h2>
<div id="glossary" class="section level3 unnumbered">
<h3>Glossary</h3>
<dl>
<dt>Response:</dt>
<dd><p>The variable who‘s distribution one seeks to investigate.</p>
</dd>
<dt>Explanatory Variable:</dt>
<dd><p>A variable that may affect the distribution of the response.</p>
</dd>
</dl>
</div>
<div id="discuss-in-the-forum" class="section level3 unnumbered">
<h3>Discuss in the forum</h3>
<p>Statistics has an important role in the analysis of data. However, some claim that the more important role of statistics is in the design stage when one decides how to collect the data. Good design may improve the chances that the eventual inference of the data will lead to a meaningful and trustworthy conclusion.</p>
<p>Some say that the quantity of data that is collected is most important. Other say that the quality of the data is more important than the quantity. What is your opinion?</p>
<p>When formulating your answer it may be useful to come up with an example from your past experience where the quantity of data was not sufficient. Else, you can describe a case where the quality of the data was less than satisfactory. How did these deficiencies affected the validity of the conclusions of the analysis of the data?</p>
<p>For illustration consider the surveys. Conducting the survey by the telephone may be a fast way to reach a large number of responses. However, the quality of the response may be less that the response obtained by face-to-face interviews.</p>
</div>
<div id="formulas" class="section level3 unnumbered">
<h3>Formulas:</h3>
<ul>
<li><p>Test statistic for equality of expectations: <span class="math inline">\(t = (\bar x_a - \bar x_b)/ \sqrt{s_a^2/n_a + s_b^2/n_b}\)</span>.</p></li>
<li><p>Confidence interval: <span class="math inline">\((\bar x_a - \bar x_b) \pm \mbox{\texttt{qnorm(0.975)}}\sqrt{s_a^2/n_a + s_b^2/n_b}\)</span>.</p></li>
<li><p>Test statistic for equality of variances: <span class="math inline">\(f = s_a^2/s_b^2\)</span>.</p></li>
<li><p>Confidence interval: <span class="math display">\[\big[(s_a^2/s_b^2)/\mbox{\texttt{qf(0.975,dfa,dfb)}} , (s_a^2/s_b^2)/\mbox{\texttt{qf(0.025,dfa,dfb)}}\big]\;.\]</span></p></li>
</ul>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="62">
<li id="fn62"><p>It should be noted that the redefined sequence “<code>heavy</code>” is no longer a sequence with logical components. It cannot be used, for example, as an index to another sequence in order to sellect the components that are associated with the “<code>TRUE</code>” logical value.<a href="ChapTwoSamp.html#fnref62">↩</a></p></li>
<li id="fn63"><p>In the case where the sample size is small and the observations are Normally distributed we used the <span class="math inline">\(t\)</span>-distribution instead. The percentile that was used in that case was <code>qt(0.975,n-1)</code>, the 0.975 percentile of the <span class="math inline">\(t\)</span>-distribution on <span class="math inline">\(n-1\)</span> degrees of freedom.<a href="ChapTwoSamp.html#fnref63">↩</a></p></li>
<li id="fn64"><p>It can be proved mathematically that the variance of a difference (or a sum) of two independent random variables is the sum of the variances. The situation is different when the two random variables are correlated.<a href="ChapTwoSamp.html#fnref64">↩</a></p></li>
<li id="fn65"><p>The confidence interval given in the output of the function “<code>t.test</code>” is <span class="math inline">\([0.1029150, 0.9989315]\)</span>, which is very similar, but not identical, to the confidence interval that we computed. The discrepancy stems from the selection of the percentile. We used the percentile of the normal distribution 1.96 = <code>qnorm(0.975)</code>. The function “<code>t.test</code>”, on the other hand, uses the percentile of the <span class="math inline">\(t\)</span>-distribution 1.972425 = <code>qt(0.975,191.561)</code>. Using this value instead would give <span class="math inline">\(0.550923 \pm 1.972425 \cdot 0.227135\)</span>, which coincides with the interval reported by “<code>t.test</code>”. For practical applications the difference between the two confidence intervals are not negligible.<a href="ChapTwoSamp.html#fnref65">↩</a></p></li>
<li id="fn66"><p>The Weltch <span class="math inline">\(t\)</span>-test for the comparison of two means uses the <span class="math inline">\(t\)</span>-distribution as an approximation of the null distribution of the <span class="math inline">\(T\)</span> test statistic. The number of degrees of freedom is computed by the formula: <span class="math inline">\(\mbox{\texttt{df}} = (v_a + v_b)^2/\{v_a^2/(n_a-1) + v_b^2/(n_b-1)\}\)</span>, where <span class="math inline">\(v_a = s_a^2/n_a\)</span> and <span class="math inline">\(v_b = s_b^2/n_b\)</span>.<a href="ChapTwoSamp.html#fnref66">↩</a></p></li>
<li id="fn67"><p>This statement holds when the distribution of the measurement is Normal.<a href="ChapTwoSamp.html#fnref67">↩</a></p></li>
<li id="fn68"><p>Use <span class="math inline">\(P(\mbox{\texttt{qchisq(0.025,n-1)}} \leq (n-1)S^2/V(X) \leq \mbox{\texttt{qchisq(0.975,n-1)}}) = 0.95\)</span> and rewrite the event in a format that puts the parameter in the center. The resulting 95% confidence interval is <span class="math inline">\([(n-1)S^2/\mbox{\texttt{qchisq(0.975,n-1)}},(n-1)S^2/\mbox{\texttt{qchisq(0.025,n-1)}}]\)</span>.<a href="ChapTwoSamp.html#fnref68">↩</a></p></li>
<li id="fn69"><p>The <span class="math inline">\(F\)</span> distribution is obtained when the measurement has a Normal distribution. When the distribution of the measurement is not Normal then the distribution of the given random variable will not be the <span class="math inline">\(F\)</span>-distribution.<a href="ChapTwoSamp.html#fnref69">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ChapTesting.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ChapRegression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"download": ["statthink.pdf", "thinkstat.epub", "stathink_datasets.zip"],
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
